// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mdbrain.dev/ent/asset"
	"mdbrain.dev/ent/tenant"
	"mdbrain.dev/ent/vault"
)

// AssetCreate is the builder for creating a Asset entity.
type AssetCreate struct {
	config
	mutation *AssetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *AssetCreate) SetTenantID(v string) *AssetCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetVaultID sets the "vault_id" field.
func (_c *AssetCreate) SetVaultID(v string) *AssetCreate {
	_c.mutation.SetVaultID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *AssetCreate) SetClientID(v string) *AssetCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *AssetCreate) SetPath(v string) *AssetCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *AssetCreate) SetObjectKey(v string) *AssetCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *AssetCreate) SetSizeBytes(v int64) *AssetCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *AssetCreate) SetContentType(v string) *AssetCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetMd5 sets the "md5" field.
func (_c *AssetCreate) SetMd5(v string) *AssetCreate {
	_c.mutation.SetMd5(v)
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AssetCreate) SetDeletedAt(v int64) *AssetCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableDeletedAt(v *int64) *AssetCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AssetCreate) SetCreatedAt(v time.Time) *AssetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableCreatedAt(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AssetCreate) SetUpdatedAt(v time.Time) *AssetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableUpdatedAt(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AssetCreate) SetID(v string) *AssetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *AssetCreate) SetTenant(v *Tenant) *AssetCreate {
	return _c.SetTenantID(v.ID)
}

// SetVault sets the "vault" edge to the Vault entity.
func (_c *AssetCreate) SetVault(v *Vault) *AssetCreate {
	return _c.SetVaultID(v.ID)
}

// Mutation returns the AssetMutation object of the builder.
func (_c *AssetCreate) Mutation() *AssetMutation {
	return _c.mutation
}

// Save creates the Asset in the database.
func (_c *AssetCreate) Save(ctx context.Context) (*Asset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetCreate) SaveX(ctx context.Context) *Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := asset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := asset.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Asset.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := asset.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Asset.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VaultID(); !ok {
		return &ValidationError{Name: "vault_id", err: errors.New(`ent: missing required field "Asset.vault_id"`)}
	}
	if v, ok := _c.mutation.VaultID(); ok {
		if err := asset.VaultIDValidator(v); err != nil {
			return &ValidationError{Name: "vault_id", err: fmt.Errorf(`ent: validator failed for field "Asset.vault_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "Asset.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := asset.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Asset.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Asset.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := asset.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Asset.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "Asset.object_key"`)}
	}
	if v, ok := _c.mutation.ObjectKey(); ok {
		if err := asset.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "Asset.object_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "Asset.size_bytes"`)}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "Asset.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := asset.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "Asset.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Md5(); !ok {
		return &ValidationError{Name: "md5", err: errors.New(`ent: missing required field "Asset.md5"`)}
	}
	if v, ok := _c.mutation.Md5(); ok {
		if err := asset.Md5Validator(v); err != nil {
			return &ValidationError{Name: "md5", err: fmt.Errorf(`ent: validator failed for field "Asset.md5": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Asset.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Asset.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := asset.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Asset.id": %w`, err)}
		}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Asset.tenant"`)}
	}
	if len(_c.mutation.VaultIDs()) == 0 {
		return &ValidationError{Name: "vault", err: errors.New(`ent: missing required edge "Asset.vault"`)}
	}
	return nil
}

func (_c *AssetCreate) sqlSave(ctx context.Context) (*Asset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Asset.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetCreate) createSpec() (*Asset, *sqlgraph.CreateSpec) {
	var (
		_node = &Asset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(asset.Table, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(asset.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(asset.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(asset.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(asset.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(asset.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.Md5(); ok {
		_spec.SetField(asset.FieldMd5, field.TypeString, value)
		_node.Md5 = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(asset.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(asset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.VaultTable,
			Columns: []string{asset.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VaultID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Asset.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *AssetCreate) OnConflict(opts ...sql.ConflictOption) *AssetUpsertOne {
	_c.conflict = opts
	return &AssetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AssetCreate) OnConflictColumns(columns ...string) *AssetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AssetUpsertOne{
		create: _c,
	}
}

type (
	// AssetUpsertOne is the builder for "upsert"-ing
	//  one Asset node.
	AssetUpsertOne struct {
		create *AssetCreate
	}

	// AssetUpsert is the "OnConflict" setter.
	AssetUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *AssetUpsert) SetTenantID(v string) *AssetUpsert {
	u.Set(asset.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AssetUpsert) UpdateTenantID() *AssetUpsert {
	u.SetExcluded(asset.FieldTenantID)
	return u
}

// SetVaultID sets the "vault_id" field.
func (u *AssetUpsert) SetVaultID(v string) *AssetUpsert {
	u.Set(asset.FieldVaultID, v)
	return u
}

// UpdateVaultID sets the "vault_id" field to the value that was provided on create.
func (u *AssetUpsert) UpdateVaultID() *AssetUpsert {
	u.SetExcluded(asset.FieldVaultID)
	return u
}

// SetClientID sets the "client_id" field.
func (u *AssetUpsert) SetClientID(v string) *AssetUpsert {
	u.Set(asset.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AssetUpsert) UpdateClientID() *AssetUpsert {
	u.SetExcluded(asset.FieldClientID)
	return u
}

// SetPath sets the "path" field.
func (u *AssetUpsert) SetPath(v string) *AssetUpsert {
	u.Set(asset.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AssetUpsert) UpdatePath() *AssetUpsert {
	u.SetExcluded(asset.FieldPath)
	return u
}

// SetObjectKey sets the "object_key" field.
func (u *AssetUpsert) SetObjectKey(v string) *AssetUpsert {
	u.Set(asset.FieldObjectKey, v)
	return u
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *AssetUpsert) UpdateObjectKey() *AssetUpsert {
	u.SetExcluded(asset.FieldObjectKey)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *AssetUpsert) SetSizeBytes(v int64) *AssetUpsert {
	u.Set(asset.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *AssetUpsert) UpdateSizeBytes() *AssetUpsert {
	u.SetExcluded(asset.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *AssetUpsert) AddSizeBytes(v int64) *AssetUpsert {
	u.Add(asset.FieldSizeBytes, v)
	return u
}

// SetContentType sets the "content_type" field.
func (u *AssetUpsert) SetContentType(v string) *AssetUpsert {
	u.Set(asset.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *AssetUpsert) UpdateContentType() *AssetUpsert {
	u.SetExcluded(asset.FieldContentType)
	return u
}

// SetMd5 sets the "md5" field.
func (u *AssetUpsert) SetMd5(v string) *AssetUpsert {
	u.Set(asset.FieldMd5, v)
	return u
}

// UpdateMd5 sets the "md5" field to the value that was provided on create.
func (u *AssetUpsert) UpdateMd5() *AssetUpsert {
	u.SetExcluded(asset.FieldMd5)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AssetUpsert) SetDeletedAt(v int64) *AssetUpsert {
	u.Set(asset.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AssetUpsert) UpdateDeletedAt() *AssetUpsert {
	u.SetExcluded(asset.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AssetUpsert) AddDeletedAt(v int64) *AssetUpsert {
	u.Add(asset.FieldDeletedAt, v)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AssetUpsert) ClearDeletedAt() *AssetUpsert {
	u.SetNull(asset.FieldDeletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AssetUpsert) SetUpdatedAt(v time.Time) *AssetUpsert {
	u.Set(asset.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AssetUpsert) UpdateUpdatedAt() *AssetUpsert {
	u.SetExcluded(asset.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(asset.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AssetUpsertOne) UpdateNewValues() *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(asset.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(asset.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Asset.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AssetUpsertOne) Ignore() *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetUpsertOne) DoNothing() *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetCreate.OnConflict
// documentation for more info.
func (u *AssetUpsertOne) Update(set func(*AssetUpsert)) *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *AssetUpsertOne) SetTenantID(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateTenantID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateTenantID()
	})
}

// SetVaultID sets the "vault_id" field.
func (u *AssetUpsertOne) SetVaultID(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetVaultID(v)
	})
}

// UpdateVaultID sets the "vault_id" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateVaultID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateVaultID()
	})
}

// SetClientID sets the "client_id" field.
func (u *AssetUpsertOne) SetClientID(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateClientID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateClientID()
	})
}

// SetPath sets the "path" field.
func (u *AssetUpsertOne) SetPath(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdatePath() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdatePath()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *AssetUpsertOne) SetObjectKey(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateObjectKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateObjectKey()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *AssetUpsertOne) SetSizeBytes(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *AssetUpsertOne) AddSizeBytes(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateSizeBytes() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetContentType sets the "content_type" field.
func (u *AssetUpsertOne) SetContentType(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateContentType() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateContentType()
	})
}

// SetMd5 sets the "md5" field.
func (u *AssetUpsertOne) SetMd5(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetMd5(v)
	})
}

// UpdateMd5 sets the "md5" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateMd5() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMd5()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AssetUpsertOne) SetDeletedAt(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AssetUpsertOne) AddDeletedAt(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateDeletedAt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AssetUpsertOne) ClearDeletedAt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AssetUpsertOne) SetUpdatedAt(v time.Time) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateUpdatedAt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AssetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AssetUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AssetUpsertOne.ID is not supported by MySQL driver. Use AssetUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AssetUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AssetCreateBulk is the builder for creating many Asset entities in bulk.
type AssetCreateBulk struct {
	config
	err      error
	builders []*AssetCreate
	conflict []sql.ConflictOption
}

// Save creates the Asset entities in the database.
func (_c *AssetCreateBulk) Save(ctx context.Context) ([]*Asset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Asset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetCreateBulk) SaveX(ctx context.Context) []*Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Asset.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *AssetCreateBulk) OnConflict(opts ...sql.ConflictOption) *AssetUpsertBulk {
	_c.conflict = opts
	return &AssetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AssetCreateBulk) OnConflictColumns(columns ...string) *AssetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AssetUpsertBulk{
		create: _c,
	}
}

// AssetUpsertBulk is the builder for "upsert"-ing
// a bulk of Asset nodes.
type AssetUpsertBulk struct {
	create *AssetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(asset.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AssetUpsertBulk) UpdateNewValues() *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(asset.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(asset.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AssetUpsertBulk) Ignore() *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetUpsertBulk) DoNothing() *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetCreateBulk.OnConflict
// documentation for more info.
func (u *AssetUpsertBulk) Update(set func(*AssetUpsert)) *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *AssetUpsertBulk) SetTenantID(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateTenantID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateTenantID()
	})
}

// SetVaultID sets the "vault_id" field.
func (u *AssetUpsertBulk) SetVaultID(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetVaultID(v)
	})
}

// UpdateVaultID sets the "vault_id" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateVaultID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateVaultID()
	})
}

// SetClientID sets the "client_id" field.
func (u *AssetUpsertBulk) SetClientID(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateClientID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateClientID()
	})
}

// SetPath sets the "path" field.
func (u *AssetUpsertBulk) SetPath(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdatePath() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdatePath()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *AssetUpsertBulk) SetObjectKey(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateObjectKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateObjectKey()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *AssetUpsertBulk) SetSizeBytes(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *AssetUpsertBulk) AddSizeBytes(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateSizeBytes() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetContentType sets the "content_type" field.
func (u *AssetUpsertBulk) SetContentType(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateContentType() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateContentType()
	})
}

// SetMd5 sets the "md5" field.
func (u *AssetUpsertBulk) SetMd5(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetMd5(v)
	})
}

// UpdateMd5 sets the "md5" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateMd5() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMd5()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AssetUpsertBulk) SetDeletedAt(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AssetUpsertBulk) AddDeletedAt(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateDeletedAt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AssetUpsertBulk) ClearDeletedAt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AssetUpsertBulk) SetUpdatedAt(v time.Time) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateUpdatedAt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AssetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AssetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
