// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mdbrain.dev/ent/asset"
	"mdbrain.dev/ent/predicate"
	"mdbrain.dev/ent/tenant"
	"mdbrain.dev/ent/vault"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks    []Hook
	mutation *AssetMutation
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AssetUpdate) SetTenantID(v string) *AssetUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableTenantID(v *string) *AssetUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetVaultID sets the "vault_id" field.
func (_u *AssetUpdate) SetVaultID(v string) *AssetUpdate {
	_u.mutation.SetVaultID(v)
	return _u
}

// SetNillableVaultID sets the "vault_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableVaultID(v *string) *AssetUpdate {
	if v != nil {
		_u.SetVaultID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AssetUpdate) SetClientID(v string) *AssetUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableClientID(v *string) *AssetUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *AssetUpdate) SetPath(v string) *AssetUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AssetUpdate) SetNillablePath(v *string) *AssetUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *AssetUpdate) SetObjectKey(v string) *AssetUpdate {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableObjectKey(v *string) *AssetUpdate {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *AssetUpdate) SetSizeBytes(v int64) *AssetUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableSizeBytes(v *int64) *AssetUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *AssetUpdate) AddSizeBytes(v int64) *AssetUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *AssetUpdate) SetContentType(v string) *AssetUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableContentType(v *string) *AssetUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetMd5 sets the "md5" field.
func (_u *AssetUpdate) SetMd5(v string) *AssetUpdate {
	_u.mutation.SetMd5(v)
	return _u
}

// SetNillableMd5 sets the "md5" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableMd5(v *string) *AssetUpdate {
	if v != nil {
		_u.SetMd5(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AssetUpdate) SetDeletedAt(v int64) *AssetUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableDeletedAt(v *int64) *AssetUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AssetUpdate) AddDeletedAt(v int64) *AssetUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AssetUpdate) ClearDeletedAt() *AssetUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetUpdate) SetUpdatedAt(v time.Time) *AssetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *AssetUpdate) SetTenant(v *Tenant) *AssetUpdate {
	return _u.SetTenantID(v.ID)
}

// SetVault sets the "vault" edge to the Vault entity.
func (_u *AssetUpdate) SetVault(v *Vault) *AssetUpdate {
	return _u.SetVaultID(v.ID)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdate) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *AssetUpdate) ClearTenant() *AssetUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearVault clears the "vault" edge to the Vault entity.
func (_u *AssetUpdate) ClearVault() *AssetUpdate {
	_u.mutation.ClearVault()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := asset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := asset.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Asset.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultID(); ok {
		if err := asset.VaultIDValidator(v); err != nil {
			return &ValidationError{Name: "vault_id", err: fmt.Errorf(`ent: validator failed for field "Asset.vault_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := asset.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Asset.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := asset.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Asset.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := asset.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "Asset.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := asset.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "Asset.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Md5(); ok {
		if err := asset.Md5Validator(v); err != nil {
			return &ValidationError{Name: "md5", err: fmt.Errorf(`ent: validator failed for field "Asset.md5": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.tenant"`)
	}
	if _u.mutation.VaultCleared() && len(_u.mutation.VaultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.vault"`)
	}
	return nil
}

func (_u *AssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(asset.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(asset.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(asset.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(asset.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(asset.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(asset.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Md5(); ok {
		_spec.SetField(asset.FieldMd5, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(asset.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(asset.FieldDeletedAt, field.TypeInt64, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(asset.FieldDeletedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.VaultTable,
			Columns: []string{asset.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.VaultTable,
			Columns: []string{asset.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *AssetUpdateOne) SetTenantID(v string) *AssetUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableTenantID(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetVaultID sets the "vault_id" field.
func (_u *AssetUpdateOne) SetVaultID(v string) *AssetUpdateOne {
	_u.mutation.SetVaultID(v)
	return _u
}

// SetNillableVaultID sets the "vault_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableVaultID(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetVaultID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AssetUpdateOne) SetClientID(v string) *AssetUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableClientID(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *AssetUpdateOne) SetPath(v string) *AssetUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillablePath(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *AssetUpdateOne) SetObjectKey(v string) *AssetUpdateOne {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableObjectKey(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *AssetUpdateOne) SetSizeBytes(v int64) *AssetUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableSizeBytes(v *int64) *AssetUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *AssetUpdateOne) AddSizeBytes(v int64) *AssetUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *AssetUpdateOne) SetContentType(v string) *AssetUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableContentType(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetMd5 sets the "md5" field.
func (_u *AssetUpdateOne) SetMd5(v string) *AssetUpdateOne {
	_u.mutation.SetMd5(v)
	return _u
}

// SetNillableMd5 sets the "md5" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableMd5(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetMd5(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AssetUpdateOne) SetDeletedAt(v int64) *AssetUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableDeletedAt(v *int64) *AssetUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *AssetUpdateOne) AddDeletedAt(v int64) *AssetUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AssetUpdateOne) ClearDeletedAt() *AssetUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetUpdateOne) SetUpdatedAt(v time.Time) *AssetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *AssetUpdateOne) SetTenant(v *Tenant) *AssetUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetVault sets the "vault" edge to the Vault entity.
func (_u *AssetUpdateOne) SetVault(v *Vault) *AssetUpdateOne {
	return _u.SetVaultID(v.ID)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdateOne) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *AssetUpdateOne) ClearTenant() *AssetUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearVault clears the "vault" edge to the Vault entity.
func (_u *AssetUpdateOne) ClearVault() *AssetUpdateOne {
	_u.mutation.ClearVault()
	return _u
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdateOne) Where(ps ...predicate.Asset) *AssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Asset entity.
func (_u *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := asset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := asset.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Asset.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultID(); ok {
		if err := asset.VaultIDValidator(v); err != nil {
			return &ValidationError{Name: "vault_id", err: fmt.Errorf(`ent: validator failed for field "Asset.vault_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := asset.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Asset.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := asset.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Asset.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := asset.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "Asset.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := asset.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "Asset.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Md5(); ok {
		if err := asset.Md5Validator(v); err != nil {
			return &ValidationError{Name: "md5", err: fmt.Errorf(`ent: validator failed for field "Asset.md5": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.tenant"`)
	}
	if _u.mutation.VaultCleared() && len(_u.mutation.VaultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.vault"`)
	}
	return nil
}

func (_u *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(asset.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(asset.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(asset.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(asset.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(asset.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(asset.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Md5(); ok {
		_spec.SetField(asset.FieldMd5, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(asset.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(asset.FieldDeletedAt, field.TypeInt64, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(asset.FieldDeletedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.VaultTable,
			Columns: []string{asset.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.VaultTable,
			Columns: []string{asset.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Asset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
