// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mdbrain.dev/ent/noteassetref"
	"mdbrain.dev/ent/vault"
)

// NoteAssetRefCreate is the builder for creating a NoteAssetRef entity.
type NoteAssetRefCreate struct {
	config
	mutation *NoteAssetRefMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetVaultID sets the "vault_id" field.
func (_c *NoteAssetRefCreate) SetVaultID(v string) *NoteAssetRefCreate {
	_c.mutation.SetVaultID(v)
	return _c
}

// SetNoteClientID sets the "note_client_id" field.
func (_c *NoteAssetRefCreate) SetNoteClientID(v string) *NoteAssetRefCreate {
	_c.mutation.SetNoteClientID(v)
	return _c
}

// SetAssetClientID sets the "asset_client_id" field.
func (_c *NoteAssetRefCreate) SetAssetClientID(v string) *NoteAssetRefCreate {
	_c.mutation.SetAssetClientID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NoteAssetRefCreate) SetCreatedAt(v time.Time) *NoteAssetRefCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NoteAssetRefCreate) SetNillableCreatedAt(v *time.Time) *NoteAssetRefCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NoteAssetRefCreate) SetID(v string) *NoteAssetRefCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetVault sets the "vault" edge to the Vault entity.
func (_c *NoteAssetRefCreate) SetVault(v *Vault) *NoteAssetRefCreate {
	return _c.SetVaultID(v.ID)
}

// Mutation returns the NoteAssetRefMutation object of the builder.
func (_c *NoteAssetRefCreate) Mutation() *NoteAssetRefMutation {
	return _c.mutation
}

// Save creates the NoteAssetRef in the database.
func (_c *NoteAssetRefCreate) Save(ctx context.Context) (*NoteAssetRef, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NoteAssetRefCreate) SaveX(ctx context.Context) *NoteAssetRef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NoteAssetRefCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NoteAssetRefCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NoteAssetRefCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := noteassetref.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NoteAssetRefCreate) check() error {
	if _, ok := _c.mutation.VaultID(); !ok {
		return &ValidationError{Name: "vault_id", err: errors.New(`ent: missing required field "NoteAssetRef.vault_id"`)}
	}
	if v, ok := _c.mutation.VaultID(); ok {
		if err := noteassetref.VaultIDValidator(v); err != nil {
			return &ValidationError{Name: "vault_id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.vault_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NoteClientID(); !ok {
		return &ValidationError{Name: "note_client_id", err: errors.New(`ent: missing required field "NoteAssetRef.note_client_id"`)}
	}
	if v, ok := _c.mutation.NoteClientID(); ok {
		if err := noteassetref.NoteClientIDValidator(v); err != nil {
			return &ValidationError{Name: "note_client_id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.note_client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AssetClientID(); !ok {
		return &ValidationError{Name: "asset_client_id", err: errors.New(`ent: missing required field "NoteAssetRef.asset_client_id"`)}
	}
	if v, ok := _c.mutation.AssetClientID(); ok {
		if err := noteassetref.AssetClientIDValidator(v); err != nil {
			return &ValidationError{Name: "asset_client_id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.asset_client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NoteAssetRef.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := noteassetref.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.id": %w`, err)}
		}
	}
	if len(_c.mutation.VaultIDs()) == 0 {
		return &ValidationError{Name: "vault", err: errors.New(`ent: missing required edge "NoteAssetRef.vault"`)}
	}
	return nil
}

func (_c *NoteAssetRefCreate) sqlSave(ctx context.Context) (*NoteAssetRef, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NoteAssetRef.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NoteAssetRefCreate) createSpec() (*NoteAssetRef, *sqlgraph.CreateSpec) {
	var (
		_node = &NoteAssetRef{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(noteassetref.Table, sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.NoteClientID(); ok {
		_spec.SetField(noteassetref.FieldNoteClientID, field.TypeString, value)
		_node.NoteClientID = value
	}
	if value, ok := _c.mutation.AssetClientID(); ok {
		_spec.SetField(noteassetref.FieldAssetClientID, field.TypeString, value)
		_node.AssetClientID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(noteassetref.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteassetref.VaultTable,
			Columns: []string{noteassetref.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VaultID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NoteAssetRef.Create().
//		SetVaultID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NoteAssetRefUpsert) {
//			SetVaultID(v+v).
//		}).
//		Exec(ctx)
func (_c *NoteAssetRefCreate) OnConflict(opts ...sql.ConflictOption) *NoteAssetRefUpsertOne {
	_c.conflict = opts
	return &NoteAssetRefUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NoteAssetRef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NoteAssetRefCreate) OnConflictColumns(columns ...string) *NoteAssetRefUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NoteAssetRefUpsertOne{
		create: _c,
	}
}

type (
	// NoteAssetRefUpsertOne is the builder for "upsert"-ing
	//  one NoteAssetRef node.
	NoteAssetRefUpsertOne struct {
		create *NoteAssetRefCreate
	}

	// NoteAssetRefUpsert is the "OnConflict" setter.
	NoteAssetRefUpsert struct {
		*sql.UpdateSet
	}
)

// SetVaultID sets the "vault_id" field.
func (u *NoteAssetRefUpsert) SetVaultID(v string) *NoteAssetRefUpsert {
	u.Set(noteassetref.FieldVaultID, v)
	return u
}

// UpdateVaultID sets the "vault_id" field to the value that was provided on create.
func (u *NoteAssetRefUpsert) UpdateVaultID() *NoteAssetRefUpsert {
	u.SetExcluded(noteassetref.FieldVaultID)
	return u
}

// SetNoteClientID sets the "note_client_id" field.
func (u *NoteAssetRefUpsert) SetNoteClientID(v string) *NoteAssetRefUpsert {
	u.Set(noteassetref.FieldNoteClientID, v)
	return u
}

// UpdateNoteClientID sets the "note_client_id" field to the value that was provided on create.
func (u *NoteAssetRefUpsert) UpdateNoteClientID() *NoteAssetRefUpsert {
	u.SetExcluded(noteassetref.FieldNoteClientID)
	return u
}

// SetAssetClientID sets the "asset_client_id" field.
func (u *NoteAssetRefUpsert) SetAssetClientID(v string) *NoteAssetRefUpsert {
	u.Set(noteassetref.FieldAssetClientID, v)
	return u
}

// UpdateAssetClientID sets the "asset_client_id" field to the value that was provided on create.
func (u *NoteAssetRefUpsert) UpdateAssetClientID() *NoteAssetRefUpsert {
	u.SetExcluded(noteassetref.FieldAssetClientID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NoteAssetRef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(noteassetref.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NoteAssetRefUpsertOne) UpdateNewValues() *NoteAssetRefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(noteassetref.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(noteassetref.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NoteAssetRef.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NoteAssetRefUpsertOne) Ignore() *NoteAssetRefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NoteAssetRefUpsertOne) DoNothing() *NoteAssetRefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NoteAssetRefCreate.OnConflict
// documentation for more info.
func (u *NoteAssetRefUpsertOne) Update(set func(*NoteAssetRefUpsert)) *NoteAssetRefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NoteAssetRefUpsert{UpdateSet: update})
	}))
	return u
}

// SetVaultID sets the "vault_id" field.
func (u *NoteAssetRefUpsertOne) SetVaultID(v string) *NoteAssetRefUpsertOne {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.SetVaultID(v)
	})
}

// UpdateVaultID sets the "vault_id" field to the value that was provided on create.
func (u *NoteAssetRefUpsertOne) UpdateVaultID() *NoteAssetRefUpsertOne {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.UpdateVaultID()
	})
}

// SetNoteClientID sets the "note_client_id" field.
func (u *NoteAssetRefUpsertOne) SetNoteClientID(v string) *NoteAssetRefUpsertOne {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.SetNoteClientID(v)
	})
}

// UpdateNoteClientID sets the "note_client_id" field to the value that was provided on create.
func (u *NoteAssetRefUpsertOne) UpdateNoteClientID() *NoteAssetRefUpsertOne {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.UpdateNoteClientID()
	})
}

// SetAssetClientID sets the "asset_client_id" field.
func (u *NoteAssetRefUpsertOne) SetAssetClientID(v string) *NoteAssetRefUpsertOne {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.SetAssetClientID(v)
	})
}

// UpdateAssetClientID sets the "asset_client_id" field to the value that was provided on create.
func (u *NoteAssetRefUpsertOne) UpdateAssetClientID() *NoteAssetRefUpsertOne {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.UpdateAssetClientID()
	})
}

// Exec executes the query.
func (u *NoteAssetRefUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NoteAssetRefCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NoteAssetRefUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NoteAssetRefUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NoteAssetRefUpsertOne.ID is not supported by MySQL driver. Use NoteAssetRefUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NoteAssetRefUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NoteAssetRefCreateBulk is the builder for creating many NoteAssetRef entities in bulk.
type NoteAssetRefCreateBulk struct {
	config
	err      error
	builders []*NoteAssetRefCreate
	conflict []sql.ConflictOption
}

// Save creates the NoteAssetRef entities in the database.
func (_c *NoteAssetRefCreateBulk) Save(ctx context.Context) ([]*NoteAssetRef, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NoteAssetRef, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NoteAssetRefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NoteAssetRefCreateBulk) SaveX(ctx context.Context) []*NoteAssetRef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NoteAssetRefCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NoteAssetRefCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NoteAssetRef.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NoteAssetRefUpsert) {
//			SetVaultID(v+v).
//		}).
//		Exec(ctx)
func (_c *NoteAssetRefCreateBulk) OnConflict(opts ...sql.ConflictOption) *NoteAssetRefUpsertBulk {
	_c.conflict = opts
	return &NoteAssetRefUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NoteAssetRef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NoteAssetRefCreateBulk) OnConflictColumns(columns ...string) *NoteAssetRefUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NoteAssetRefUpsertBulk{
		create: _c,
	}
}

// NoteAssetRefUpsertBulk is the builder for "upsert"-ing
// a bulk of NoteAssetRef nodes.
type NoteAssetRefUpsertBulk struct {
	create *NoteAssetRefCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NoteAssetRef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(noteassetref.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NoteAssetRefUpsertBulk) UpdateNewValues() *NoteAssetRefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(noteassetref.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(noteassetref.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NoteAssetRef.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NoteAssetRefUpsertBulk) Ignore() *NoteAssetRefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NoteAssetRefUpsertBulk) DoNothing() *NoteAssetRefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NoteAssetRefCreateBulk.OnConflict
// documentation for more info.
func (u *NoteAssetRefUpsertBulk) Update(set func(*NoteAssetRefUpsert)) *NoteAssetRefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NoteAssetRefUpsert{UpdateSet: update})
	}))
	return u
}

// SetVaultID sets the "vault_id" field.
func (u *NoteAssetRefUpsertBulk) SetVaultID(v string) *NoteAssetRefUpsertBulk {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.SetVaultID(v)
	})
}

// UpdateVaultID sets the "vault_id" field to the value that was provided on create.
func (u *NoteAssetRefUpsertBulk) UpdateVaultID() *NoteAssetRefUpsertBulk {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.UpdateVaultID()
	})
}

// SetNoteClientID sets the "note_client_id" field.
func (u *NoteAssetRefUpsertBulk) SetNoteClientID(v string) *NoteAssetRefUpsertBulk {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.SetNoteClientID(v)
	})
}

// UpdateNoteClientID sets the "note_client_id" field to the value that was provided on create.
func (u *NoteAssetRefUpsertBulk) UpdateNoteClientID() *NoteAssetRefUpsertBulk {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.UpdateNoteClientID()
	})
}

// SetAssetClientID sets the "asset_client_id" field.
func (u *NoteAssetRefUpsertBulk) SetAssetClientID(v string) *NoteAssetRefUpsertBulk {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.SetAssetClientID(v)
	})
}

// UpdateAssetClientID sets the "asset_client_id" field to the value that was provided on create.
func (u *NoteAssetRefUpsertBulk) UpdateAssetClientID() *NoteAssetRefUpsertBulk {
	return u.Update(func(s *NoteAssetRefUpsert) {
		s.UpdateAssetClientID()
	})
}

// Exec executes the query.
func (u *NoteAssetRefUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NoteAssetRefCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NoteAssetRefCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NoteAssetRefUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
