// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mdbrain.dev/ent/note"
	"mdbrain.dev/ent/tenant"
	"mdbrain.dev/ent/vault"
)

// NoteCreate is the builder for creating a Note entity.
type NoteCreate struct {
	config
	mutation *NoteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *NoteCreate) SetTenantID(v string) *NoteCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetVaultID sets the "vault_id" field.
func (_c *NoteCreate) SetVaultID(v string) *NoteCreate {
	_c.mutation.SetVaultID(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *NoteCreate) SetPath(v string) *NoteCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *NoteCreate) SetClientID(v string) *NoteCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *NoteCreate) SetContent(v string) *NoteCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *NoteCreate) SetNillableContent(v *string) *NoteCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *NoteCreate) SetMetadata(v string) *NoteCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_c *NoteCreate) SetNillableMetadata(v *string) *NoteCreate {
	if v != nil {
		_c.SetMetadata(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *NoteCreate) SetHash(v string) *NoteCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_c *NoteCreate) SetNillableHash(v *string) *NoteCreate {
	if v != nil {
		_c.SetHash(*v)
	}
	return _c
}

// SetMtime sets the "mtime" field.
func (_c *NoteCreate) SetMtime(v string) *NoteCreate {
	_c.mutation.SetMtime(v)
	return _c
}

// SetNillableMtime sets the "mtime" field if the given value is not nil.
func (_c *NoteCreate) SetNillableMtime(v *string) *NoteCreate {
	if v != nil {
		_c.SetMtime(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *NoteCreate) SetDeletedAt(v int64) *NoteCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *NoteCreate) SetNillableDeletedAt(v *int64) *NoteCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NoteCreate) SetCreatedAt(v time.Time) *NoteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NoteCreate) SetNillableCreatedAt(v *time.Time) *NoteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NoteCreate) SetUpdatedAt(v time.Time) *NoteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NoteCreate) SetNillableUpdatedAt(v *time.Time) *NoteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NoteCreate) SetID(v string) *NoteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *NoteCreate) SetTenant(v *Tenant) *NoteCreate {
	return _c.SetTenantID(v.ID)
}

// SetVault sets the "vault" edge to the Vault entity.
func (_c *NoteCreate) SetVault(v *Vault) *NoteCreate {
	return _c.SetVaultID(v.ID)
}

// Mutation returns the NoteMutation object of the builder.
func (_c *NoteCreate) Mutation() *NoteMutation {
	return _c.mutation
}

// Save creates the Note in the database.
func (_c *NoteCreate) Save(ctx context.Context) (*Note, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NoteCreate) SaveX(ctx context.Context) *Note {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NoteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NoteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NoteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := note.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := note.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NoteCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Note.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := note.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Note.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VaultID(); !ok {
		return &ValidationError{Name: "vault_id", err: errors.New(`ent: missing required field "Note.vault_id"`)}
	}
	if v, ok := _c.mutation.VaultID(); ok {
		if err := note.VaultIDValidator(v); err != nil {
			return &ValidationError{Name: "vault_id", err: fmt.Errorf(`ent: validator failed for field "Note.vault_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Note.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := note.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Note.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "Note.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := note.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Note.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Note.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Note.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := note.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Note.id": %w`, err)}
		}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Note.tenant"`)}
	}
	if len(_c.mutation.VaultIDs()) == 0 {
		return &ValidationError{Name: "vault", err: errors.New(`ent: missing required edge "Note.vault"`)}
	}
	return nil
}

func (_c *NoteCreate) sqlSave(ctx context.Context) (*Note, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Note.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NoteCreate) createSpec() (*Note, *sqlgraph.CreateSpec) {
	var (
		_node = &Note{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(note.Table, sqlgraph.NewFieldSpec(note.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(note.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(note.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(note.FieldContent, field.TypeString, value)
		_node.Content = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(note.FieldMetadata, field.TypeString, value)
		_node.Metadata = &value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(note.FieldHash, field.TypeString, value)
		_node.Hash = &value
	}
	if value, ok := _c.mutation.Mtime(); ok {
		_spec.SetField(note.FieldMtime, field.TypeString, value)
		_node.Mtime = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(note.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(note.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(note.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.TenantTable,
			Columns: []string{note.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.VaultTable,
			Columns: []string{note.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VaultID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Note.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NoteUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *NoteCreate) OnConflict(opts ...sql.ConflictOption) *NoteUpsertOne {
	_c.conflict = opts
	return &NoteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NoteCreate) OnConflictColumns(columns ...string) *NoteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NoteUpsertOne{
		create: _c,
	}
}

type (
	// NoteUpsertOne is the builder for "upsert"-ing
	//  one Note node.
	NoteUpsertOne struct {
		create *NoteCreate
	}

	// NoteUpsert is the "OnConflict" setter.
	NoteUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *NoteUpsert) SetTenantID(v string) *NoteUpsert {
	u.Set(note.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *NoteUpsert) UpdateTenantID() *NoteUpsert {
	u.SetExcluded(note.FieldTenantID)
	return u
}

// SetVaultID sets the "vault_id" field.
func (u *NoteUpsert) SetVaultID(v string) *NoteUpsert {
	u.Set(note.FieldVaultID, v)
	return u
}

// UpdateVaultID sets the "vault_id" field to the value that was provided on create.
func (u *NoteUpsert) UpdateVaultID() *NoteUpsert {
	u.SetExcluded(note.FieldVaultID)
	return u
}

// SetPath sets the "path" field.
func (u *NoteUpsert) SetPath(v string) *NoteUpsert {
	u.Set(note.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *NoteUpsert) UpdatePath() *NoteUpsert {
	u.SetExcluded(note.FieldPath)
	return u
}

// SetClientID sets the "client_id" field.
func (u *NoteUpsert) SetClientID(v string) *NoteUpsert {
	u.Set(note.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *NoteUpsert) UpdateClientID() *NoteUpsert {
	u.SetExcluded(note.FieldClientID)
	return u
}

// SetContent sets the "content" field.
func (u *NoteUpsert) SetContent(v string) *NoteUpsert {
	u.Set(note.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NoteUpsert) UpdateContent() *NoteUpsert {
	u.SetExcluded(note.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *NoteUpsert) ClearContent() *NoteUpsert {
	u.SetNull(note.FieldContent)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *NoteUpsert) SetMetadata(v string) *NoteUpsert {
	u.Set(note.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *NoteUpsert) UpdateMetadata() *NoteUpsert {
	u.SetExcluded(note.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *NoteUpsert) ClearMetadata() *NoteUpsert {
	u.SetNull(note.FieldMetadata)
	return u
}

// SetHash sets the "hash" field.
func (u *NoteUpsert) SetHash(v string) *NoteUpsert {
	u.Set(note.FieldHash, v)
	return u
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *NoteUpsert) UpdateHash() *NoteUpsert {
	u.SetExcluded(note.FieldHash)
	return u
}

// ClearHash clears the value of the "hash" field.
func (u *NoteUpsert) ClearHash() *NoteUpsert {
	u.SetNull(note.FieldHash)
	return u
}

// SetMtime sets the "mtime" field.
func (u *NoteUpsert) SetMtime(v string) *NoteUpsert {
	u.Set(note.FieldMtime, v)
	return u
}

// UpdateMtime sets the "mtime" field to the value that was provided on create.
func (u *NoteUpsert) UpdateMtime() *NoteUpsert {
	u.SetExcluded(note.FieldMtime)
	return u
}

// ClearMtime clears the value of the "mtime" field.
func (u *NoteUpsert) ClearMtime() *NoteUpsert {
	u.SetNull(note.FieldMtime)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NoteUpsert) SetDeletedAt(v int64) *NoteUpsert {
	u.Set(note.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NoteUpsert) UpdateDeletedAt() *NoteUpsert {
	u.SetExcluded(note.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *NoteUpsert) AddDeletedAt(v int64) *NoteUpsert {
	u.Add(note.FieldDeletedAt, v)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NoteUpsert) ClearDeletedAt() *NoteUpsert {
	u.SetNull(note.FieldDeletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NoteUpsert) SetUpdatedAt(v time.Time) *NoteUpsert {
	u.Set(note.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NoteUpsert) UpdateUpdatedAt() *NoteUpsert {
	u.SetExcluded(note.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(note.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NoteUpsertOne) UpdateNewValues() *NoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(note.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(note.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Note.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NoteUpsertOne) Ignore() *NoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NoteUpsertOne) DoNothing() *NoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NoteCreate.OnConflict
// documentation for more info.
func (u *NoteUpsertOne) Update(set func(*NoteUpsert)) *NoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NoteUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *NoteUpsertOne) SetTenantID(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateTenantID() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateTenantID()
	})
}

// SetVaultID sets the "vault_id" field.
func (u *NoteUpsertOne) SetVaultID(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetVaultID(v)
	})
}

// UpdateVaultID sets the "vault_id" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateVaultID() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateVaultID()
	})
}

// SetPath sets the "path" field.
func (u *NoteUpsertOne) SetPath(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdatePath() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdatePath()
	})
}

// SetClientID sets the "client_id" field.
func (u *NoteUpsertOne) SetClientID(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateClientID() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateClientID()
	})
}

// SetContent sets the "content" field.
func (u *NoteUpsertOne) SetContent(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateContent() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *NoteUpsertOne) ClearContent() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.ClearContent()
	})
}

// SetMetadata sets the "metadata" field.
func (u *NoteUpsertOne) SetMetadata(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateMetadata() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *NoteUpsertOne) ClearMetadata() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.ClearMetadata()
	})
}

// SetHash sets the "hash" field.
func (u *NoteUpsertOne) SetHash(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateHash() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateHash()
	})
}

// ClearHash clears the value of the "hash" field.
func (u *NoteUpsertOne) ClearHash() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.ClearHash()
	})
}

// SetMtime sets the "mtime" field.
func (u *NoteUpsertOne) SetMtime(v string) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetMtime(v)
	})
}

// UpdateMtime sets the "mtime" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateMtime() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateMtime()
	})
}

// ClearMtime clears the value of the "mtime" field.
func (u *NoteUpsertOne) ClearMtime() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.ClearMtime()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NoteUpsertOne) SetDeletedAt(v int64) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *NoteUpsertOne) AddDeletedAt(v int64) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateDeletedAt() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NoteUpsertOne) ClearDeletedAt() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NoteUpsertOne) SetUpdatedAt(v time.Time) *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NoteUpsertOne) UpdateUpdatedAt() *NoteUpsertOne {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NoteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NoteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NoteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NoteUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NoteUpsertOne.ID is not supported by MySQL driver. Use NoteUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NoteUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NoteCreateBulk is the builder for creating many Note entities in bulk.
type NoteCreateBulk struct {
	config
	err      error
	builders []*NoteCreate
	conflict []sql.ConflictOption
}

// Save creates the Note entities in the database.
func (_c *NoteCreateBulk) Save(ctx context.Context) ([]*Note, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Note, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NoteCreateBulk) SaveX(ctx context.Context) []*Note {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NoteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NoteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Note.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NoteUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *NoteCreateBulk) OnConflict(opts ...sql.ConflictOption) *NoteUpsertBulk {
	_c.conflict = opts
	return &NoteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NoteCreateBulk) OnConflictColumns(columns ...string) *NoteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NoteUpsertBulk{
		create: _c,
	}
}

// NoteUpsertBulk is the builder for "upsert"-ing
// a bulk of Note nodes.
type NoteUpsertBulk struct {
	create *NoteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(note.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NoteUpsertBulk) UpdateNewValues() *NoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(note.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(note.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Note.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NoteUpsertBulk) Ignore() *NoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NoteUpsertBulk) DoNothing() *NoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NoteCreateBulk.OnConflict
// documentation for more info.
func (u *NoteUpsertBulk) Update(set func(*NoteUpsert)) *NoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NoteUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *NoteUpsertBulk) SetTenantID(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateTenantID() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateTenantID()
	})
}

// SetVaultID sets the "vault_id" field.
func (u *NoteUpsertBulk) SetVaultID(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetVaultID(v)
	})
}

// UpdateVaultID sets the "vault_id" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateVaultID() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateVaultID()
	})
}

// SetPath sets the "path" field.
func (u *NoteUpsertBulk) SetPath(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdatePath() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdatePath()
	})
}

// SetClientID sets the "client_id" field.
func (u *NoteUpsertBulk) SetClientID(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateClientID() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateClientID()
	})
}

// SetContent sets the "content" field.
func (u *NoteUpsertBulk) SetContent(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateContent() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *NoteUpsertBulk) ClearContent() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.ClearContent()
	})
}

// SetMetadata sets the "metadata" field.
func (u *NoteUpsertBulk) SetMetadata(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateMetadata() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *NoteUpsertBulk) ClearMetadata() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.ClearMetadata()
	})
}

// SetHash sets the "hash" field.
func (u *NoteUpsertBulk) SetHash(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateHash() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateHash()
	})
}

// ClearHash clears the value of the "hash" field.
func (u *NoteUpsertBulk) ClearHash() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.ClearHash()
	})
}

// SetMtime sets the "mtime" field.
func (u *NoteUpsertBulk) SetMtime(v string) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetMtime(v)
	})
}

// UpdateMtime sets the "mtime" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateMtime() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateMtime()
	})
}

// ClearMtime clears the value of the "mtime" field.
func (u *NoteUpsertBulk) ClearMtime() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.ClearMtime()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NoteUpsertBulk) SetDeletedAt(v int64) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *NoteUpsertBulk) AddDeletedAt(v int64) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateDeletedAt() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NoteUpsertBulk) ClearDeletedAt() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NoteUpsertBulk) SetUpdatedAt(v time.Time) *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NoteUpsertBulk) UpdateUpdatedAt() *NoteUpsertBulk {
	return u.Update(func(s *NoteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NoteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NoteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NoteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NoteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
