// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mdbrain.dev/ent/noteassetref"
	"mdbrain.dev/ent/predicate"
	"mdbrain.dev/ent/vault"
)

// NoteAssetRefUpdate is the builder for updating NoteAssetRef entities.
type NoteAssetRefUpdate struct {
	config
	hooks    []Hook
	mutation *NoteAssetRefMutation
}

// Where appends a list predicates to the NoteAssetRefUpdate builder.
func (_u *NoteAssetRefUpdate) Where(ps ...predicate.NoteAssetRef) *NoteAssetRefUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVaultID sets the "vault_id" field.
func (_u *NoteAssetRefUpdate) SetVaultID(v string) *NoteAssetRefUpdate {
	_u.mutation.SetVaultID(v)
	return _u
}

// SetNillableVaultID sets the "vault_id" field if the given value is not nil.
func (_u *NoteAssetRefUpdate) SetNillableVaultID(v *string) *NoteAssetRefUpdate {
	if v != nil {
		_u.SetVaultID(*v)
	}
	return _u
}

// SetNoteClientID sets the "note_client_id" field.
func (_u *NoteAssetRefUpdate) SetNoteClientID(v string) *NoteAssetRefUpdate {
	_u.mutation.SetNoteClientID(v)
	return _u
}

// SetNillableNoteClientID sets the "note_client_id" field if the given value is not nil.
func (_u *NoteAssetRefUpdate) SetNillableNoteClientID(v *string) *NoteAssetRefUpdate {
	if v != nil {
		_u.SetNoteClientID(*v)
	}
	return _u
}

// SetAssetClientID sets the "asset_client_id" field.
func (_u *NoteAssetRefUpdate) SetAssetClientID(v string) *NoteAssetRefUpdate {
	_u.mutation.SetAssetClientID(v)
	return _u
}

// SetNillableAssetClientID sets the "asset_client_id" field if the given value is not nil.
func (_u *NoteAssetRefUpdate) SetNillableAssetClientID(v *string) *NoteAssetRefUpdate {
	if v != nil {
		_u.SetAssetClientID(*v)
	}
	return _u
}

// SetVault sets the "vault" edge to the Vault entity.
func (_u *NoteAssetRefUpdate) SetVault(v *Vault) *NoteAssetRefUpdate {
	return _u.SetVaultID(v.ID)
}

// Mutation returns the NoteAssetRefMutation object of the builder.
func (_u *NoteAssetRefUpdate) Mutation() *NoteAssetRefMutation {
	return _u.mutation
}

// ClearVault clears the "vault" edge to the Vault entity.
func (_u *NoteAssetRefUpdate) ClearVault() *NoteAssetRefUpdate {
	_u.mutation.ClearVault()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NoteAssetRefUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteAssetRefUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NoteAssetRefUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteAssetRefUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteAssetRefUpdate) check() error {
	if v, ok := _u.mutation.VaultID(); ok {
		if err := noteassetref.VaultIDValidator(v); err != nil {
			return &ValidationError{Name: "vault_id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.vault_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NoteClientID(); ok {
		if err := noteassetref.NoteClientIDValidator(v); err != nil {
			return &ValidationError{Name: "note_client_id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.note_client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssetClientID(); ok {
		if err := noteassetref.AssetClientIDValidator(v); err != nil {
			return &ValidationError{Name: "asset_client_id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.asset_client_id": %w`, err)}
		}
	}
	if _u.mutation.VaultCleared() && len(_u.mutation.VaultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NoteAssetRef.vault"`)
	}
	return nil
}

func (_u *NoteAssetRefUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(noteassetref.Table, noteassetref.Columns, sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NoteClientID(); ok {
		_spec.SetField(noteassetref.FieldNoteClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetClientID(); ok {
		_spec.SetField(noteassetref.FieldAssetClientID, field.TypeString, value)
	}
	if _u.mutation.VaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteassetref.VaultTable,
			Columns: []string{noteassetref.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteassetref.VaultTable,
			Columns: []string{noteassetref.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{noteassetref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NoteAssetRefUpdateOne is the builder for updating a single NoteAssetRef entity.
type NoteAssetRefUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoteAssetRefMutation
}

// SetVaultID sets the "vault_id" field.
func (_u *NoteAssetRefUpdateOne) SetVaultID(v string) *NoteAssetRefUpdateOne {
	_u.mutation.SetVaultID(v)
	return _u
}

// SetNillableVaultID sets the "vault_id" field if the given value is not nil.
func (_u *NoteAssetRefUpdateOne) SetNillableVaultID(v *string) *NoteAssetRefUpdateOne {
	if v != nil {
		_u.SetVaultID(*v)
	}
	return _u
}

// SetNoteClientID sets the "note_client_id" field.
func (_u *NoteAssetRefUpdateOne) SetNoteClientID(v string) *NoteAssetRefUpdateOne {
	_u.mutation.SetNoteClientID(v)
	return _u
}

// SetNillableNoteClientID sets the "note_client_id" field if the given value is not nil.
func (_u *NoteAssetRefUpdateOne) SetNillableNoteClientID(v *string) *NoteAssetRefUpdateOne {
	if v != nil {
		_u.SetNoteClientID(*v)
	}
	return _u
}

// SetAssetClientID sets the "asset_client_id" field.
func (_u *NoteAssetRefUpdateOne) SetAssetClientID(v string) *NoteAssetRefUpdateOne {
	_u.mutation.SetAssetClientID(v)
	return _u
}

// SetNillableAssetClientID sets the "asset_client_id" field if the given value is not nil.
func (_u *NoteAssetRefUpdateOne) SetNillableAssetClientID(v *string) *NoteAssetRefUpdateOne {
	if v != nil {
		_u.SetAssetClientID(*v)
	}
	return _u
}

// SetVault sets the "vault" edge to the Vault entity.
func (_u *NoteAssetRefUpdateOne) SetVault(v *Vault) *NoteAssetRefUpdateOne {
	return _u.SetVaultID(v.ID)
}

// Mutation returns the NoteAssetRefMutation object of the builder.
func (_u *NoteAssetRefUpdateOne) Mutation() *NoteAssetRefMutation {
	return _u.mutation
}

// ClearVault clears the "vault" edge to the Vault entity.
func (_u *NoteAssetRefUpdateOne) ClearVault() *NoteAssetRefUpdateOne {
	_u.mutation.ClearVault()
	return _u
}

// Where appends a list predicates to the NoteAssetRefUpdate builder.
func (_u *NoteAssetRefUpdateOne) Where(ps ...predicate.NoteAssetRef) *NoteAssetRefUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NoteAssetRefUpdateOne) Select(field string, fields ...string) *NoteAssetRefUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NoteAssetRef entity.
func (_u *NoteAssetRefUpdateOne) Save(ctx context.Context) (*NoteAssetRef, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteAssetRefUpdateOne) SaveX(ctx context.Context) *NoteAssetRef {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NoteAssetRefUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteAssetRefUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteAssetRefUpdateOne) check() error {
	if v, ok := _u.mutation.VaultID(); ok {
		if err := noteassetref.VaultIDValidator(v); err != nil {
			return &ValidationError{Name: "vault_id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.vault_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NoteClientID(); ok {
		if err := noteassetref.NoteClientIDValidator(v); err != nil {
			return &ValidationError{Name: "note_client_id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.note_client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssetClientID(); ok {
		if err := noteassetref.AssetClientIDValidator(v); err != nil {
			return &ValidationError{Name: "asset_client_id", err: fmt.Errorf(`ent: validator failed for field "NoteAssetRef.asset_client_id": %w`, err)}
		}
	}
	if _u.mutation.VaultCleared() && len(_u.mutation.VaultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NoteAssetRef.vault"`)
	}
	return nil
}

func (_u *NoteAssetRefUpdateOne) sqlSave(ctx context.Context) (_node *NoteAssetRef, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(noteassetref.Table, noteassetref.Columns, sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NoteAssetRef.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, noteassetref.FieldID)
		for _, f := range fields {
			if !noteassetref.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != noteassetref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NoteClientID(); ok {
		_spec.SetField(noteassetref.FieldNoteClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetClientID(); ok {
		_spec.SetField(noteassetref.FieldAssetClientID, field.TypeString, value)
	}
	if _u.mutation.VaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteassetref.VaultTable,
			Columns: []string{noteassetref.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteassetref.VaultTable,
			Columns: []string{noteassetref.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NoteAssetRef{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{noteassetref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
