// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mdbrain.dev/ent/note"
	"mdbrain.dev/ent/predicate"
	"mdbrain.dev/ent/tenant"
	"mdbrain.dev/ent/vault"
)

// NoteUpdate is the builder for updating Note entities.
type NoteUpdate struct {
	config
	hooks    []Hook
	mutation *NoteMutation
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdate) Where(ps ...predicate.Note) *NoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *NoteUpdate) SetTenantID(v string) *NoteUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableTenantID(v *string) *NoteUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetVaultID sets the "vault_id" field.
func (_u *NoteUpdate) SetVaultID(v string) *NoteUpdate {
	_u.mutation.SetVaultID(v)
	return _u
}

// SetNillableVaultID sets the "vault_id" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableVaultID(v *string) *NoteUpdate {
	if v != nil {
		_u.SetVaultID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *NoteUpdate) SetPath(v string) *NoteUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *NoteUpdate) SetNillablePath(v *string) *NoteUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *NoteUpdate) SetClientID(v string) *NoteUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableClientID(v *string) *NoteUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NoteUpdate) SetContent(v string) *NoteUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableContent(v *string) *NoteUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *NoteUpdate) ClearContent() *NoteUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NoteUpdate) SetMetadata(v string) *NoteUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableMetadata(v *string) *NoteUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NoteUpdate) ClearMetadata() *NoteUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetHash sets the "hash" field.
func (_u *NoteUpdate) SetHash(v string) *NoteUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableHash(v *string) *NoteUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// ClearHash clears the value of the "hash" field.
func (_u *NoteUpdate) ClearHash() *NoteUpdate {
	_u.mutation.ClearHash()
	return _u
}

// SetMtime sets the "mtime" field.
func (_u *NoteUpdate) SetMtime(v string) *NoteUpdate {
	_u.mutation.SetMtime(v)
	return _u
}

// SetNillableMtime sets the "mtime" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableMtime(v *string) *NoteUpdate {
	if v != nil {
		_u.SetMtime(*v)
	}
	return _u
}

// ClearMtime clears the value of the "mtime" field.
func (_u *NoteUpdate) ClearMtime() *NoteUpdate {
	_u.mutation.ClearMtime()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NoteUpdate) SetDeletedAt(v int64) *NoteUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableDeletedAt(v *int64) *NoteUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *NoteUpdate) AddDeletedAt(v int64) *NoteUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NoteUpdate) ClearDeletedAt() *NoteUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NoteUpdate) SetUpdatedAt(v time.Time) *NoteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *NoteUpdate) SetTenant(v *Tenant) *NoteUpdate {
	return _u.SetTenantID(v.ID)
}

// SetVault sets the "vault" edge to the Vault entity.
func (_u *NoteUpdate) SetVault(v *Vault) *NoteUpdate {
	return _u.SetVaultID(v.ID)
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdate) Mutation() *NoteMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *NoteUpdate) ClearTenant() *NoteUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearVault clears the "vault" edge to the Vault entity.
func (_u *NoteUpdate) ClearVault() *NoteUpdate {
	_u.mutation.ClearVault()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NoteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NoteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := note.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := note.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Note.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultID(); ok {
		if err := note.VaultIDValidator(v); err != nil {
			return &ValidationError{Name: "vault_id", err: fmt.Errorf(`ent: validator failed for field "Note.vault_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := note.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Note.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := note.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Note.client_id": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.tenant"`)
	}
	if _u.mutation.VaultCleared() && len(_u.mutation.VaultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.vault"`)
	}
	return nil
}

func (_u *NoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(note.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(note.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(note.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(note.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(note.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(note.FieldMetadata, field.TypeString)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(note.FieldHash, field.TypeString, value)
	}
	if _u.mutation.HashCleared() {
		_spec.ClearField(note.FieldHash, field.TypeString)
	}
	if value, ok := _u.mutation.Mtime(); ok {
		_spec.SetField(note.FieldMtime, field.TypeString, value)
	}
	if _u.mutation.MtimeCleared() {
		_spec.ClearField(note.FieldMtime, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(note.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(note.FieldDeletedAt, field.TypeInt64, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(note.FieldDeletedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(note.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.TenantTable,
			Columns: []string{note.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.TenantTable,
			Columns: []string{note.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.VaultTable,
			Columns: []string{note.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.VaultTable,
			Columns: []string{note.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NoteUpdateOne is the builder for updating a single Note entity.
type NoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoteMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *NoteUpdateOne) SetTenantID(v string) *NoteUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableTenantID(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetVaultID sets the "vault_id" field.
func (_u *NoteUpdateOne) SetVaultID(v string) *NoteUpdateOne {
	_u.mutation.SetVaultID(v)
	return _u
}

// SetNillableVaultID sets the "vault_id" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableVaultID(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetVaultID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *NoteUpdateOne) SetPath(v string) *NoteUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillablePath(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *NoteUpdateOne) SetClientID(v string) *NoteUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableClientID(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NoteUpdateOne) SetContent(v string) *NoteUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableContent(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *NoteUpdateOne) ClearContent() *NoteUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NoteUpdateOne) SetMetadata(v string) *NoteUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableMetadata(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NoteUpdateOne) ClearMetadata() *NoteUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetHash sets the "hash" field.
func (_u *NoteUpdateOne) SetHash(v string) *NoteUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableHash(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// ClearHash clears the value of the "hash" field.
func (_u *NoteUpdateOne) ClearHash() *NoteUpdateOne {
	_u.mutation.ClearHash()
	return _u
}

// SetMtime sets the "mtime" field.
func (_u *NoteUpdateOne) SetMtime(v string) *NoteUpdateOne {
	_u.mutation.SetMtime(v)
	return _u
}

// SetNillableMtime sets the "mtime" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableMtime(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetMtime(*v)
	}
	return _u
}

// ClearMtime clears the value of the "mtime" field.
func (_u *NoteUpdateOne) ClearMtime() *NoteUpdateOne {
	_u.mutation.ClearMtime()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NoteUpdateOne) SetDeletedAt(v int64) *NoteUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableDeletedAt(v *int64) *NoteUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *NoteUpdateOne) AddDeletedAt(v int64) *NoteUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NoteUpdateOne) ClearDeletedAt() *NoteUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NoteUpdateOne) SetUpdatedAt(v time.Time) *NoteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *NoteUpdateOne) SetTenant(v *Tenant) *NoteUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetVault sets the "vault" edge to the Vault entity.
func (_u *NoteUpdateOne) SetVault(v *Vault) *NoteUpdateOne {
	return _u.SetVaultID(v.ID)
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdateOne) Mutation() *NoteMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *NoteUpdateOne) ClearTenant() *NoteUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearVault clears the "vault" edge to the Vault entity.
func (_u *NoteUpdateOne) ClearVault() *NoteUpdateOne {
	_u.mutation.ClearVault()
	return _u
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdateOne) Where(ps ...predicate.Note) *NoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NoteUpdateOne) Select(field string, fields ...string) *NoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Note entity.
func (_u *NoteUpdateOne) Save(ctx context.Context) (*Note, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdateOne) SaveX(ctx context.Context) *Note {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NoteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := note.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := note.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Note.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultID(); ok {
		if err := note.VaultIDValidator(v); err != nil {
			return &ValidationError{Name: "vault_id", err: fmt.Errorf(`ent: validator failed for field "Note.vault_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := note.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Note.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := note.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Note.client_id": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.tenant"`)
	}
	if _u.mutation.VaultCleared() && len(_u.mutation.VaultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.vault"`)
	}
	return nil
}

func (_u *NoteUpdateOne) sqlSave(ctx context.Context) (_node *Note, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Note.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, note.FieldID)
		for _, f := range fields {
			if !note.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != note.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(note.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(note.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(note.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(note.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(note.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(note.FieldMetadata, field.TypeString)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(note.FieldHash, field.TypeString, value)
	}
	if _u.mutation.HashCleared() {
		_spec.ClearField(note.FieldHash, field.TypeString)
	}
	if value, ok := _u.mutation.Mtime(); ok {
		_spec.SetField(note.FieldMtime, field.TypeString, value)
	}
	if _u.mutation.MtimeCleared() {
		_spec.ClearField(note.FieldMtime, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(note.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(note.FieldDeletedAt, field.TypeInt64, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(note.FieldDeletedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(note.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.TenantTable,
			Columns: []string{note.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.TenantTable,
			Columns: []string{note.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.VaultTable,
			Columns: []string{note.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.VaultTable,
			Columns: []string{note.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Note{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
