// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mdbrain.dev/ent/noteassetref"
	"mdbrain.dev/ent/predicate"
)

// NoteAssetRefDelete is the builder for deleting a NoteAssetRef entity.
type NoteAssetRefDelete struct {
	config
	hooks    []Hook
	mutation *NoteAssetRefMutation
}

// Where appends a list predicates to the NoteAssetRefDelete builder.
func (_d *NoteAssetRefDelete) Where(ps ...predicate.NoteAssetRef) *NoteAssetRefDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NoteAssetRefDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NoteAssetRefDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NoteAssetRefDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(noteassetref.Table, sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NoteAssetRefDeleteOne is the builder for deleting a single NoteAssetRef entity.
type NoteAssetRefDeleteOne struct {
	_d *NoteAssetRefDelete
}

// Where appends a list predicates to the NoteAssetRefDelete builder.
func (_d *NoteAssetRefDeleteOne) Where(ps ...predicate.NoteAssetRef) *NoteAssetRefDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NoteAssetRefDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{noteassetref.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NoteAssetRefDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
