// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"mdbrain.dev/ent/tenant"
	"mdbrain.dev/ent/vault"
)

// Vault is the model entity for the Vault schema.
type Vault struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain *string `json:"domain,omitempty"`
	// SyncKey holds the value of the "sync_key" field.
	SyncKey string `json:"sync_key,omitempty"`
	// ClientType holds the value of the "client_type" field.
	ClientType string `json:"client_type,omitempty"`
	// RootNoteID holds the value of the "root_note_id" field.
	RootNoteID *string `json:"root_note_id,omitempty"`
	// LogoObjectKey holds the value of the "logo_object_key" field.
	LogoObjectKey *string `json:"logo_object_key,omitempty"`
	// CustomHeadHTML holds the value of the "custom_head_html" field.
	CustomHeadHTML *string `json:"custom_head_html,omitempty"`
	// LastPublishAt holds the value of the "last_publish_at" field.
	LastPublishAt *time.Time `json:"last_publish_at,omitempty"`
	// LastPublishStatus holds the value of the "last_publish_status" field.
	LastPublishStatus string `json:"last_publish_status,omitempty"`
	// LastPublishErrorCode holds the value of the "last_publish_error_code" field.
	LastPublishErrorCode *string `json:"last_publish_error_code,omitempty"`
	// LastPublishErrorMessage holds the value of the "last_publish_error_message" field.
	LastPublishErrorMessage *string `json:"last_publish_error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VaultQuery when eager-loading is set.
	Edges        VaultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VaultEdges holds the relations/edges for other nodes in the graph.
type VaultEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Notes holds the value of the notes edge.
	Notes []*Note `json:"notes,omitempty"`
	// Assets holds the value of the assets edge.
	Assets []*Asset `json:"assets,omitempty"`
	// NoteLinks holds the value of the note_links edge.
	NoteLinks []*NoteLink `json:"note_links,omitempty"`
	// NoteAssetRefs holds the value of the note_asset_refs edge.
	NoteAssetRefs []*NoteAssetRef `json:"note_asset_refs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VaultEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// NotesOrErr returns the Notes value or an error if the edge
// was not loaded in eager-loading.
func (e VaultEdges) NotesOrErr() ([]*Note, error) {
	if e.loadedTypes[1] {
		return e.Notes, nil
	}
	return nil, &NotLoadedError{edge: "notes"}
}

// AssetsOrErr returns the Assets value or an error if the edge
// was not loaded in eager-loading.
func (e VaultEdges) AssetsOrErr() ([]*Asset, error) {
	if e.loadedTypes[2] {
		return e.Assets, nil
	}
	return nil, &NotLoadedError{edge: "assets"}
}

// NoteLinksOrErr returns the NoteLinks value or an error if the edge
// was not loaded in eager-loading.
func (e VaultEdges) NoteLinksOrErr() ([]*NoteLink, error) {
	if e.loadedTypes[3] {
		return e.NoteLinks, nil
	}
	return nil, &NotLoadedError{edge: "note_links"}
}

// NoteAssetRefsOrErr returns the NoteAssetRefs value or an error if the edge
// was not loaded in eager-loading.
func (e VaultEdges) NoteAssetRefsOrErr() ([]*NoteAssetRef, error) {
	if e.loadedTypes[4] {
		return e.NoteAssetRefs, nil
	}
	return nil, &NotLoadedError{edge: "note_asset_refs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Vault) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vault.FieldID, vault.FieldTenantID, vault.FieldName, vault.FieldDomain, vault.FieldSyncKey, vault.FieldClientType, vault.FieldRootNoteID, vault.FieldLogoObjectKey, vault.FieldCustomHeadHTML, vault.FieldLastPublishStatus, vault.FieldLastPublishErrorCode, vault.FieldLastPublishErrorMessage:
			values[i] = new(sql.NullString)
		case vault.FieldLastPublishAt, vault.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Vault fields.
func (_m *Vault) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vault.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case vault.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case vault.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case vault.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				_m.Domain = new(string)
				*_m.Domain = value.String
			}
		case vault.FieldSyncKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_key", values[i])
			} else if value.Valid {
				_m.SyncKey = value.String
			}
		case vault.FieldClientType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_type", values[i])
			} else if value.Valid {
				_m.ClientType = value.String
			}
		case vault.FieldRootNoteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field root_note_id", values[i])
			} else if value.Valid {
				_m.RootNoteID = new(string)
				*_m.RootNoteID = value.String
			}
		case vault.FieldLogoObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo_object_key", values[i])
			} else if value.Valid {
				_m.LogoObjectKey = new(string)
				*_m.LogoObjectKey = value.String
			}
		case vault.FieldCustomHeadHTML:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_head_html", values[i])
			} else if value.Valid {
				_m.CustomHeadHTML = new(string)
				*_m.CustomHeadHTML = value.String
			}
		case vault.FieldLastPublishAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_publish_at", values[i])
			} else if value.Valid {
				_m.LastPublishAt = new(time.Time)
				*_m.LastPublishAt = value.Time
			}
		case vault.FieldLastPublishStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_publish_status", values[i])
			} else if value.Valid {
				_m.LastPublishStatus = value.String
			}
		case vault.FieldLastPublishErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_publish_error_code", values[i])
			} else if value.Valid {
				_m.LastPublishErrorCode = new(string)
				*_m.LastPublishErrorCode = value.String
			}
		case vault.FieldLastPublishErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_publish_error_message", values[i])
			} else if value.Valid {
				_m.LastPublishErrorMessage = new(string)
				*_m.LastPublishErrorMessage = value.String
			}
		case vault.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Vault.
// This includes values selected through modifiers, order, etc.
func (_m *Vault) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Vault entity.
func (_m *Vault) QueryTenant() *TenantQuery {
	return NewVaultClient(_m.config).QueryTenant(_m)
}

// QueryNotes queries the "notes" edge of the Vault entity.
func (_m *Vault) QueryNotes() *NoteQuery {
	return NewVaultClient(_m.config).QueryNotes(_m)
}

// QueryAssets queries the "assets" edge of the Vault entity.
func (_m *Vault) QueryAssets() *AssetQuery {
	return NewVaultClient(_m.config).QueryAssets(_m)
}

// QueryNoteLinks queries the "note_links" edge of the Vault entity.
func (_m *Vault) QueryNoteLinks() *NoteLinkQuery {
	return NewVaultClient(_m.config).QueryNoteLinks(_m)
}

// QueryNoteAssetRefs queries the "note_asset_refs" edge of the Vault entity.
func (_m *Vault) QueryNoteAssetRefs() *NoteAssetRefQuery {
	return NewVaultClient(_m.config).QueryNoteAssetRefs(_m)
}

// Update returns a builder for updating this Vault.
// Note that you need to call Vault.Unwrap() before calling this method if this Vault
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Vault) Update() *VaultUpdateOne {
	return NewVaultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Vault entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Vault) Unwrap() *Vault {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Vault is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Vault) String() string {
	var builder strings.Builder
	builder.WriteString("Vault(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Domain; v != nil {
		builder.WriteString("domain=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sync_key=")
	builder.WriteString(_m.SyncKey)
	builder.WriteString(", ")
	builder.WriteString("client_type=")
	builder.WriteString(_m.ClientType)
	builder.WriteString(", ")
	if v := _m.RootNoteID; v != nil {
		builder.WriteString("root_note_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LogoObjectKey; v != nil {
		builder.WriteString("logo_object_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CustomHeadHTML; v != nil {
		builder.WriteString("custom_head_html=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastPublishAt; v != nil {
		builder.WriteString("last_publish_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_publish_status=")
	builder.WriteString(_m.LastPublishStatus)
	builder.WriteString(", ")
	if v := _m.LastPublishErrorCode; v != nil {
		builder.WriteString("last_publish_error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastPublishErrorMessage; v != nil {
		builder.WriteString("last_publish_error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Vaults is a parsable slice of Vault.
type Vaults []*Vault
