// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mdbrain.dev/ent/asset"
	"mdbrain.dev/ent/note"
	"mdbrain.dev/ent/noteassetref"
	"mdbrain.dev/ent/notelink"
	"mdbrain.dev/ent/tenant"
	"mdbrain.dev/ent/vault"
)

// VaultCreate is the builder for creating a Vault entity.
type VaultCreate struct {
	config
	mutation *VaultMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *VaultCreate) SetTenantID(v string) *VaultCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *VaultCreate) SetName(v string) *VaultCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *VaultCreate) SetDomain(v string) *VaultCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *VaultCreate) SetNillableDomain(v *string) *VaultCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetSyncKey sets the "sync_key" field.
func (_c *VaultCreate) SetSyncKey(v string) *VaultCreate {
	_c.mutation.SetSyncKey(v)
	return _c
}

// SetClientType sets the "client_type" field.
func (_c *VaultCreate) SetClientType(v string) *VaultCreate {
	_c.mutation.SetClientType(v)
	return _c
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_c *VaultCreate) SetNillableClientType(v *string) *VaultCreate {
	if v != nil {
		_c.SetClientType(*v)
	}
	return _c
}

// SetRootNoteID sets the "root_note_id" field.
func (_c *VaultCreate) SetRootNoteID(v string) *VaultCreate {
	_c.mutation.SetRootNoteID(v)
	return _c
}

// SetNillableRootNoteID sets the "root_note_id" field if the given value is not nil.
func (_c *VaultCreate) SetNillableRootNoteID(v *string) *VaultCreate {
	if v != nil {
		_c.SetRootNoteID(*v)
	}
	return _c
}

// SetLogoObjectKey sets the "logo_object_key" field.
func (_c *VaultCreate) SetLogoObjectKey(v string) *VaultCreate {
	_c.mutation.SetLogoObjectKey(v)
	return _c
}

// SetNillableLogoObjectKey sets the "logo_object_key" field if the given value is not nil.
func (_c *VaultCreate) SetNillableLogoObjectKey(v *string) *VaultCreate {
	if v != nil {
		_c.SetLogoObjectKey(*v)
	}
	return _c
}

// SetCustomHeadHTML sets the "custom_head_html" field.
func (_c *VaultCreate) SetCustomHeadHTML(v string) *VaultCreate {
	_c.mutation.SetCustomHeadHTML(v)
	return _c
}

// SetNillableCustomHeadHTML sets the "custom_head_html" field if the given value is not nil.
func (_c *VaultCreate) SetNillableCustomHeadHTML(v *string) *VaultCreate {
	if v != nil {
		_c.SetCustomHeadHTML(*v)
	}
	return _c
}

// SetLastPublishAt sets the "last_publish_at" field.
func (_c *VaultCreate) SetLastPublishAt(v time.Time) *VaultCreate {
	_c.mutation.SetLastPublishAt(v)
	return _c
}

// SetNillableLastPublishAt sets the "last_publish_at" field if the given value is not nil.
func (_c *VaultCreate) SetNillableLastPublishAt(v *time.Time) *VaultCreate {
	if v != nil {
		_c.SetLastPublishAt(*v)
	}
	return _c
}

// SetLastPublishStatus sets the "last_publish_status" field.
func (_c *VaultCreate) SetLastPublishStatus(v string) *VaultCreate {
	_c.mutation.SetLastPublishStatus(v)
	return _c
}

// SetNillableLastPublishStatus sets the "last_publish_status" field if the given value is not nil.
func (_c *VaultCreate) SetNillableLastPublishStatus(v *string) *VaultCreate {
	if v != nil {
		_c.SetLastPublishStatus(*v)
	}
	return _c
}

// SetLastPublishErrorCode sets the "last_publish_error_code" field.
func (_c *VaultCreate) SetLastPublishErrorCode(v string) *VaultCreate {
	_c.mutation.SetLastPublishErrorCode(v)
	return _c
}

// SetNillableLastPublishErrorCode sets the "last_publish_error_code" field if the given value is not nil.
func (_c *VaultCreate) SetNillableLastPublishErrorCode(v *string) *VaultCreate {
	if v != nil {
		_c.SetLastPublishErrorCode(*v)
	}
	return _c
}

// SetLastPublishErrorMessage sets the "last_publish_error_message" field.
func (_c *VaultCreate) SetLastPublishErrorMessage(v string) *VaultCreate {
	_c.mutation.SetLastPublishErrorMessage(v)
	return _c
}

// SetNillableLastPublishErrorMessage sets the "last_publish_error_message" field if the given value is not nil.
func (_c *VaultCreate) SetNillableLastPublishErrorMessage(v *string) *VaultCreate {
	if v != nil {
		_c.SetLastPublishErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VaultCreate) SetCreatedAt(v time.Time) *VaultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VaultCreate) SetNillableCreatedAt(v *time.Time) *VaultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VaultCreate) SetID(v string) *VaultCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *VaultCreate) SetTenant(v *Tenant) *VaultCreate {
	return _c.SetTenantID(v.ID)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (_c *VaultCreate) AddNoteIDs(ids ...string) *VaultCreate {
	_c.mutation.AddNoteIDs(ids...)
	return _c
}

// AddNotes adds the "notes" edges to the Note entity.
func (_c *VaultCreate) AddNotes(v ...*Note) *VaultCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNoteIDs(ids...)
}

// AddAssetIDs adds the "assets" edge to the Asset entity by IDs.
func (_c *VaultCreate) AddAssetIDs(ids ...string) *VaultCreate {
	_c.mutation.AddAssetIDs(ids...)
	return _c
}

// AddAssets adds the "assets" edges to the Asset entity.
func (_c *VaultCreate) AddAssets(v ...*Asset) *VaultCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssetIDs(ids...)
}

// AddNoteLinkIDs adds the "note_links" edge to the NoteLink entity by IDs.
func (_c *VaultCreate) AddNoteLinkIDs(ids ...string) *VaultCreate {
	_c.mutation.AddNoteLinkIDs(ids...)
	return _c
}

// AddNoteLinks adds the "note_links" edges to the NoteLink entity.
func (_c *VaultCreate) AddNoteLinks(v ...*NoteLink) *VaultCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNoteLinkIDs(ids...)
}

// AddNoteAssetRefIDs adds the "note_asset_refs" edge to the NoteAssetRef entity by IDs.
func (_c *VaultCreate) AddNoteAssetRefIDs(ids ...string) *VaultCreate {
	_c.mutation.AddNoteAssetRefIDs(ids...)
	return _c
}

// AddNoteAssetRefs adds the "note_asset_refs" edges to the NoteAssetRef entity.
func (_c *VaultCreate) AddNoteAssetRefs(v ...*NoteAssetRef) *VaultCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNoteAssetRefIDs(ids...)
}

// Mutation returns the VaultMutation object of the builder.
func (_c *VaultCreate) Mutation() *VaultMutation {
	return _c.mutation
}

// Save creates the Vault in the database.
func (_c *VaultCreate) Save(ctx context.Context) (*Vault, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VaultCreate) SaveX(ctx context.Context) *Vault {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VaultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VaultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VaultCreate) defaults() {
	if _, ok := _c.mutation.ClientType(); !ok {
		v := vault.DefaultClientType
		_c.mutation.SetClientType(v)
	}
	if _, ok := _c.mutation.LastPublishStatus(); !ok {
		v := vault.DefaultLastPublishStatus
		_c.mutation.SetLastPublishStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vault.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VaultCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Vault.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := vault.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Vault.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Vault.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := vault.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Vault.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncKey(); !ok {
		return &ValidationError{Name: "sync_key", err: errors.New(`ent: missing required field "Vault.sync_key"`)}
	}
	if v, ok := _c.mutation.SyncKey(); ok {
		if err := vault.SyncKeyValidator(v); err != nil {
			return &ValidationError{Name: "sync_key", err: fmt.Errorf(`ent: validator failed for field "Vault.sync_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientType(); !ok {
		return &ValidationError{Name: "client_type", err: errors.New(`ent: missing required field "Vault.client_type"`)}
	}
	if _, ok := _c.mutation.LastPublishStatus(); !ok {
		return &ValidationError{Name: "last_publish_status", err: errors.New(`ent: missing required field "Vault.last_publish_status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Vault.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := vault.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Vault.id": %w`, err)}
		}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Vault.tenant"`)}
	}
	return nil
}

func (_c *VaultCreate) sqlSave(ctx context.Context) (*Vault, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Vault.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VaultCreate) createSpec() (*Vault, *sqlgraph.CreateSpec) {
	var (
		_node = &Vault{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vault.Table, sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(vault.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(vault.FieldDomain, field.TypeString, value)
		_node.Domain = &value
	}
	if value, ok := _c.mutation.SyncKey(); ok {
		_spec.SetField(vault.FieldSyncKey, field.TypeString, value)
		_node.SyncKey = value
	}
	if value, ok := _c.mutation.ClientType(); ok {
		_spec.SetField(vault.FieldClientType, field.TypeString, value)
		_node.ClientType = value
	}
	if value, ok := _c.mutation.RootNoteID(); ok {
		_spec.SetField(vault.FieldRootNoteID, field.TypeString, value)
		_node.RootNoteID = &value
	}
	if value, ok := _c.mutation.LogoObjectKey(); ok {
		_spec.SetField(vault.FieldLogoObjectKey, field.TypeString, value)
		_node.LogoObjectKey = &value
	}
	if value, ok := _c.mutation.CustomHeadHTML(); ok {
		_spec.SetField(vault.FieldCustomHeadHTML, field.TypeString, value)
		_node.CustomHeadHTML = &value
	}
	if value, ok := _c.mutation.LastPublishAt(); ok {
		_spec.SetField(vault.FieldLastPublishAt, field.TypeTime, value)
		_node.LastPublishAt = &value
	}
	if value, ok := _c.mutation.LastPublishStatus(); ok {
		_spec.SetField(vault.FieldLastPublishStatus, field.TypeString, value)
		_node.LastPublishStatus = value
	}
	if value, ok := _c.mutation.LastPublishErrorCode(); ok {
		_spec.SetField(vault.FieldLastPublishErrorCode, field.TypeString, value)
		_node.LastPublishErrorCode = &value
	}
	if value, ok := _c.mutation.LastPublishErrorMessage(); ok {
		_spec.SetField(vault.FieldLastPublishErrorMessage, field.TypeString, value)
		_node.LastPublishErrorMessage = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vault.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vault.TenantTable,
			Columns: []string{vault.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NotesTable,
			Columns: []string{vault.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.AssetsTable,
			Columns: []string{vault.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NoteLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteLinksTable,
			Columns: []string{vault.NoteLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NoteAssetRefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteAssetRefsTable,
			Columns: []string{vault.NoteAssetRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Vault.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VaultUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *VaultCreate) OnConflict(opts ...sql.ConflictOption) *VaultUpsertOne {
	_c.conflict = opts
	return &VaultUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Vault.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VaultCreate) OnConflictColumns(columns ...string) *VaultUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VaultUpsertOne{
		create: _c,
	}
}

type (
	// VaultUpsertOne is the builder for "upsert"-ing
	//  one Vault node.
	VaultUpsertOne struct {
		create *VaultCreate
	}

	// VaultUpsert is the "OnConflict" setter.
	VaultUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *VaultUpsert) SetTenantID(v string) *VaultUpsert {
	u.Set(vault.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *VaultUpsert) UpdateTenantID() *VaultUpsert {
	u.SetExcluded(vault.FieldTenantID)
	return u
}

// SetName sets the "name" field.
func (u *VaultUpsert) SetName(v string) *VaultUpsert {
	u.Set(vault.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VaultUpsert) UpdateName() *VaultUpsert {
	u.SetExcluded(vault.FieldName)
	return u
}

// SetDomain sets the "domain" field.
func (u *VaultUpsert) SetDomain(v string) *VaultUpsert {
	u.Set(vault.FieldDomain, v)
	return u
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *VaultUpsert) UpdateDomain() *VaultUpsert {
	u.SetExcluded(vault.FieldDomain)
	return u
}

// ClearDomain clears the value of the "domain" field.
func (u *VaultUpsert) ClearDomain() *VaultUpsert {
	u.SetNull(vault.FieldDomain)
	return u
}

// SetSyncKey sets the "sync_key" field.
func (u *VaultUpsert) SetSyncKey(v string) *VaultUpsert {
	u.Set(vault.FieldSyncKey, v)
	return u
}

// UpdateSyncKey sets the "sync_key" field to the value that was provided on create.
func (u *VaultUpsert) UpdateSyncKey() *VaultUpsert {
	u.SetExcluded(vault.FieldSyncKey)
	return u
}

// SetClientType sets the "client_type" field.
func (u *VaultUpsert) SetClientType(v string) *VaultUpsert {
	u.Set(vault.FieldClientType, v)
	return u
}

// UpdateClientType sets the "client_type" field to the value that was provided on create.
func (u *VaultUpsert) UpdateClientType() *VaultUpsert {
	u.SetExcluded(vault.FieldClientType)
	return u
}

// SetRootNoteID sets the "root_note_id" field.
func (u *VaultUpsert) SetRootNoteID(v string) *VaultUpsert {
	u.Set(vault.FieldRootNoteID, v)
	return u
}

// UpdateRootNoteID sets the "root_note_id" field to the value that was provided on create.
func (u *VaultUpsert) UpdateRootNoteID() *VaultUpsert {
	u.SetExcluded(vault.FieldRootNoteID)
	return u
}

// ClearRootNoteID clears the value of the "root_note_id" field.
func (u *VaultUpsert) ClearRootNoteID() *VaultUpsert {
	u.SetNull(vault.FieldRootNoteID)
	return u
}

// SetLogoObjectKey sets the "logo_object_key" field.
func (u *VaultUpsert) SetLogoObjectKey(v string) *VaultUpsert {
	u.Set(vault.FieldLogoObjectKey, v)
	return u
}

// UpdateLogoObjectKey sets the "logo_object_key" field to the value that was provided on create.
func (u *VaultUpsert) UpdateLogoObjectKey() *VaultUpsert {
	u.SetExcluded(vault.FieldLogoObjectKey)
	return u
}

// ClearLogoObjectKey clears the value of the "logo_object_key" field.
func (u *VaultUpsert) ClearLogoObjectKey() *VaultUpsert {
	u.SetNull(vault.FieldLogoObjectKey)
	return u
}

// SetCustomHeadHTML sets the "custom_head_html" field.
func (u *VaultUpsert) SetCustomHeadHTML(v string) *VaultUpsert {
	u.Set(vault.FieldCustomHeadHTML, v)
	return u
}

// UpdateCustomHeadHTML sets the "custom_head_html" field to the value that was provided on create.
func (u *VaultUpsert) UpdateCustomHeadHTML() *VaultUpsert {
	u.SetExcluded(vault.FieldCustomHeadHTML)
	return u
}

// ClearCustomHeadHTML clears the value of the "custom_head_html" field.
func (u *VaultUpsert) ClearCustomHeadHTML() *VaultUpsert {
	u.SetNull(vault.FieldCustomHeadHTML)
	return u
}

// SetLastPublishAt sets the "last_publish_at" field.
func (u *VaultUpsert) SetLastPublishAt(v time.Time) *VaultUpsert {
	u.Set(vault.FieldLastPublishAt, v)
	return u
}

// UpdateLastPublishAt sets the "last_publish_at" field to the value that was provided on create.
func (u *VaultUpsert) UpdateLastPublishAt() *VaultUpsert {
	u.SetExcluded(vault.FieldLastPublishAt)
	return u
}

// ClearLastPublishAt clears the value of the "last_publish_at" field.
func (u *VaultUpsert) ClearLastPublishAt() *VaultUpsert {
	u.SetNull(vault.FieldLastPublishAt)
	return u
}

// SetLastPublishStatus sets the "last_publish_status" field.
func (u *VaultUpsert) SetLastPublishStatus(v string) *VaultUpsert {
	u.Set(vault.FieldLastPublishStatus, v)
	return u
}

// UpdateLastPublishStatus sets the "last_publish_status" field to the value that was provided on create.
func (u *VaultUpsert) UpdateLastPublishStatus() *VaultUpsert {
	u.SetExcluded(vault.FieldLastPublishStatus)
	return u
}

// SetLastPublishErrorCode sets the "last_publish_error_code" field.
func (u *VaultUpsert) SetLastPublishErrorCode(v string) *VaultUpsert {
	u.Set(vault.FieldLastPublishErrorCode, v)
	return u
}

// UpdateLastPublishErrorCode sets the "last_publish_error_code" field to the value that was provided on create.
func (u *VaultUpsert) UpdateLastPublishErrorCode() *VaultUpsert {
	u.SetExcluded(vault.FieldLastPublishErrorCode)
	return u
}

// ClearLastPublishErrorCode clears the value of the "last_publish_error_code" field.
func (u *VaultUpsert) ClearLastPublishErrorCode() *VaultUpsert {
	u.SetNull(vault.FieldLastPublishErrorCode)
	return u
}

// SetLastPublishErrorMessage sets the "last_publish_error_message" field.
func (u *VaultUpsert) SetLastPublishErrorMessage(v string) *VaultUpsert {
	u.Set(vault.FieldLastPublishErrorMessage, v)
	return u
}

// UpdateLastPublishErrorMessage sets the "last_publish_error_message" field to the value that was provided on create.
func (u *VaultUpsert) UpdateLastPublishErrorMessage() *VaultUpsert {
	u.SetExcluded(vault.FieldLastPublishErrorMessage)
	return u
}

// ClearLastPublishErrorMessage clears the value of the "last_publish_error_message" field.
func (u *VaultUpsert) ClearLastPublishErrorMessage() *VaultUpsert {
	u.SetNull(vault.FieldLastPublishErrorMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Vault.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(vault.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VaultUpsertOne) UpdateNewValues() *VaultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(vault.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(vault.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Vault.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VaultUpsertOne) Ignore() *VaultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VaultUpsertOne) DoNothing() *VaultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VaultCreate.OnConflict
// documentation for more info.
func (u *VaultUpsertOne) Update(set func(*VaultUpsert)) *VaultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VaultUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *VaultUpsertOne) SetTenantID(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateTenantID() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *VaultUpsertOne) SetName(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateName() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateName()
	})
}

// SetDomain sets the "domain" field.
func (u *VaultUpsertOne) SetDomain(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateDomain() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateDomain()
	})
}

// ClearDomain clears the value of the "domain" field.
func (u *VaultUpsertOne) ClearDomain() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.ClearDomain()
	})
}

// SetSyncKey sets the "sync_key" field.
func (u *VaultUpsertOne) SetSyncKey(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetSyncKey(v)
	})
}

// UpdateSyncKey sets the "sync_key" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateSyncKey() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateSyncKey()
	})
}

// SetClientType sets the "client_type" field.
func (u *VaultUpsertOne) SetClientType(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetClientType(v)
	})
}

// UpdateClientType sets the "client_type" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateClientType() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateClientType()
	})
}

// SetRootNoteID sets the "root_note_id" field.
func (u *VaultUpsertOne) SetRootNoteID(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetRootNoteID(v)
	})
}

// UpdateRootNoteID sets the "root_note_id" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateRootNoteID() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateRootNoteID()
	})
}

// ClearRootNoteID clears the value of the "root_note_id" field.
func (u *VaultUpsertOne) ClearRootNoteID() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.ClearRootNoteID()
	})
}

// SetLogoObjectKey sets the "logo_object_key" field.
func (u *VaultUpsertOne) SetLogoObjectKey(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetLogoObjectKey(v)
	})
}

// UpdateLogoObjectKey sets the "logo_object_key" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateLogoObjectKey() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLogoObjectKey()
	})
}

// ClearLogoObjectKey clears the value of the "logo_object_key" field.
func (u *VaultUpsertOne) ClearLogoObjectKey() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.ClearLogoObjectKey()
	})
}

// SetCustomHeadHTML sets the "custom_head_html" field.
func (u *VaultUpsertOne) SetCustomHeadHTML(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetCustomHeadHTML(v)
	})
}

// UpdateCustomHeadHTML sets the "custom_head_html" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateCustomHeadHTML() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateCustomHeadHTML()
	})
}

// ClearCustomHeadHTML clears the value of the "custom_head_html" field.
func (u *VaultUpsertOne) ClearCustomHeadHTML() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.ClearCustomHeadHTML()
	})
}

// SetLastPublishAt sets the "last_publish_at" field.
func (u *VaultUpsertOne) SetLastPublishAt(v time.Time) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetLastPublishAt(v)
	})
}

// UpdateLastPublishAt sets the "last_publish_at" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateLastPublishAt() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLastPublishAt()
	})
}

// ClearLastPublishAt clears the value of the "last_publish_at" field.
func (u *VaultUpsertOne) ClearLastPublishAt() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.ClearLastPublishAt()
	})
}

// SetLastPublishStatus sets the "last_publish_status" field.
func (u *VaultUpsertOne) SetLastPublishStatus(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetLastPublishStatus(v)
	})
}

// UpdateLastPublishStatus sets the "last_publish_status" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateLastPublishStatus() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLastPublishStatus()
	})
}

// SetLastPublishErrorCode sets the "last_publish_error_code" field.
func (u *VaultUpsertOne) SetLastPublishErrorCode(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetLastPublishErrorCode(v)
	})
}

// UpdateLastPublishErrorCode sets the "last_publish_error_code" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateLastPublishErrorCode() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLastPublishErrorCode()
	})
}

// ClearLastPublishErrorCode clears the value of the "last_publish_error_code" field.
func (u *VaultUpsertOne) ClearLastPublishErrorCode() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.ClearLastPublishErrorCode()
	})
}

// SetLastPublishErrorMessage sets the "last_publish_error_message" field.
func (u *VaultUpsertOne) SetLastPublishErrorMessage(v string) *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.SetLastPublishErrorMessage(v)
	})
}

// UpdateLastPublishErrorMessage sets the "last_publish_error_message" field to the value that was provided on create.
func (u *VaultUpsertOne) UpdateLastPublishErrorMessage() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLastPublishErrorMessage()
	})
}

// ClearLastPublishErrorMessage clears the value of the "last_publish_error_message" field.
func (u *VaultUpsertOne) ClearLastPublishErrorMessage() *VaultUpsertOne {
	return u.Update(func(s *VaultUpsert) {
		s.ClearLastPublishErrorMessage()
	})
}

// Exec executes the query.
func (u *VaultUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VaultCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VaultUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VaultUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: VaultUpsertOne.ID is not supported by MySQL driver. Use VaultUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VaultUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VaultCreateBulk is the builder for creating many Vault entities in bulk.
type VaultCreateBulk struct {
	config
	err      error
	builders []*VaultCreate
	conflict []sql.ConflictOption
}

// Save creates the Vault entities in the database.
func (_c *VaultCreateBulk) Save(ctx context.Context) ([]*Vault, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Vault, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VaultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VaultCreateBulk) SaveX(ctx context.Context) []*Vault {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VaultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VaultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Vault.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VaultUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *VaultCreateBulk) OnConflict(opts ...sql.ConflictOption) *VaultUpsertBulk {
	_c.conflict = opts
	return &VaultUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Vault.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VaultCreateBulk) OnConflictColumns(columns ...string) *VaultUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VaultUpsertBulk{
		create: _c,
	}
}

// VaultUpsertBulk is the builder for "upsert"-ing
// a bulk of Vault nodes.
type VaultUpsertBulk struct {
	create *VaultCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Vault.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(vault.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VaultUpsertBulk) UpdateNewValues() *VaultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(vault.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(vault.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Vault.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VaultUpsertBulk) Ignore() *VaultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VaultUpsertBulk) DoNothing() *VaultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VaultCreateBulk.OnConflict
// documentation for more info.
func (u *VaultUpsertBulk) Update(set func(*VaultUpsert)) *VaultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VaultUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *VaultUpsertBulk) SetTenantID(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateTenantID() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *VaultUpsertBulk) SetName(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateName() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateName()
	})
}

// SetDomain sets the "domain" field.
func (u *VaultUpsertBulk) SetDomain(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateDomain() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateDomain()
	})
}

// ClearDomain clears the value of the "domain" field.
func (u *VaultUpsertBulk) ClearDomain() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.ClearDomain()
	})
}

// SetSyncKey sets the "sync_key" field.
func (u *VaultUpsertBulk) SetSyncKey(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetSyncKey(v)
	})
}

// UpdateSyncKey sets the "sync_key" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateSyncKey() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateSyncKey()
	})
}

// SetClientType sets the "client_type" field.
func (u *VaultUpsertBulk) SetClientType(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetClientType(v)
	})
}

// UpdateClientType sets the "client_type" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateClientType() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateClientType()
	})
}

// SetRootNoteID sets the "root_note_id" field.
func (u *VaultUpsertBulk) SetRootNoteID(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetRootNoteID(v)
	})
}

// UpdateRootNoteID sets the "root_note_id" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateRootNoteID() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateRootNoteID()
	})
}

// ClearRootNoteID clears the value of the "root_note_id" field.
func (u *VaultUpsertBulk) ClearRootNoteID() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.ClearRootNoteID()
	})
}

// SetLogoObjectKey sets the "logo_object_key" field.
func (u *VaultUpsertBulk) SetLogoObjectKey(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetLogoObjectKey(v)
	})
}

// UpdateLogoObjectKey sets the "logo_object_key" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateLogoObjectKey() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLogoObjectKey()
	})
}

// ClearLogoObjectKey clears the value of the "logo_object_key" field.
func (u *VaultUpsertBulk) ClearLogoObjectKey() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.ClearLogoObjectKey()
	})
}

// SetCustomHeadHTML sets the "custom_head_html" field.
func (u *VaultUpsertBulk) SetCustomHeadHTML(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetCustomHeadHTML(v)
	})
}

// UpdateCustomHeadHTML sets the "custom_head_html" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateCustomHeadHTML() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateCustomHeadHTML()
	})
}

// ClearCustomHeadHTML clears the value of the "custom_head_html" field.
func (u *VaultUpsertBulk) ClearCustomHeadHTML() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.ClearCustomHeadHTML()
	})
}

// SetLastPublishAt sets the "last_publish_at" field.
func (u *VaultUpsertBulk) SetLastPublishAt(v time.Time) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetLastPublishAt(v)
	})
}

// UpdateLastPublishAt sets the "last_publish_at" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateLastPublishAt() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLastPublishAt()
	})
}

// ClearLastPublishAt clears the value of the "last_publish_at" field.
func (u *VaultUpsertBulk) ClearLastPublishAt() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.ClearLastPublishAt()
	})
}

// SetLastPublishStatus sets the "last_publish_status" field.
func (u *VaultUpsertBulk) SetLastPublishStatus(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetLastPublishStatus(v)
	})
}

// UpdateLastPublishStatus sets the "last_publish_status" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateLastPublishStatus() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLastPublishStatus()
	})
}

// SetLastPublishErrorCode sets the "last_publish_error_code" field.
func (u *VaultUpsertBulk) SetLastPublishErrorCode(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetLastPublishErrorCode(v)
	})
}

// UpdateLastPublishErrorCode sets the "last_publish_error_code" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateLastPublishErrorCode() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLastPublishErrorCode()
	})
}

// ClearLastPublishErrorCode clears the value of the "last_publish_error_code" field.
func (u *VaultUpsertBulk) ClearLastPublishErrorCode() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.ClearLastPublishErrorCode()
	})
}

// SetLastPublishErrorMessage sets the "last_publish_error_message" field.
func (u *VaultUpsertBulk) SetLastPublishErrorMessage(v string) *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.SetLastPublishErrorMessage(v)
	})
}

// UpdateLastPublishErrorMessage sets the "last_publish_error_message" field to the value that was provided on create.
func (u *VaultUpsertBulk) UpdateLastPublishErrorMessage() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.UpdateLastPublishErrorMessage()
	})
}

// ClearLastPublishErrorMessage clears the value of the "last_publish_error_message" field.
func (u *VaultUpsertBulk) ClearLastPublishErrorMessage() *VaultUpsertBulk {
	return u.Update(func(s *VaultUpsert) {
		s.ClearLastPublishErrorMessage()
	})
}

// Exec executes the query.
func (u *VaultUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VaultCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VaultCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VaultUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
