// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"mdbrain.dev/ent/asset"
	"mdbrain.dev/ent/note"
	"mdbrain.dev/ent/noteassetref"
	"mdbrain.dev/ent/notelink"
	"mdbrain.dev/ent/predicate"
	"mdbrain.dev/ent/tenant"
	"mdbrain.dev/ent/vault"
)

// VaultUpdate is the builder for updating Vault entities.
type VaultUpdate struct {
	config
	hooks    []Hook
	mutation *VaultMutation
}

// Where appends a list predicates to the VaultUpdate builder.
func (_u *VaultUpdate) Where(ps ...predicate.Vault) *VaultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *VaultUpdate) SetTenantID(v string) *VaultUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableTenantID(v *string) *VaultUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *VaultUpdate) SetName(v string) *VaultUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableName(v *string) *VaultUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *VaultUpdate) SetDomain(v string) *VaultUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableDomain(v *string) *VaultUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *VaultUpdate) ClearDomain() *VaultUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetSyncKey sets the "sync_key" field.
func (_u *VaultUpdate) SetSyncKey(v string) *VaultUpdate {
	_u.mutation.SetSyncKey(v)
	return _u
}

// SetNillableSyncKey sets the "sync_key" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableSyncKey(v *string) *VaultUpdate {
	if v != nil {
		_u.SetSyncKey(*v)
	}
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *VaultUpdate) SetClientType(v string) *VaultUpdate {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableClientType(v *string) *VaultUpdate {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetRootNoteID sets the "root_note_id" field.
func (_u *VaultUpdate) SetRootNoteID(v string) *VaultUpdate {
	_u.mutation.SetRootNoteID(v)
	return _u
}

// SetNillableRootNoteID sets the "root_note_id" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableRootNoteID(v *string) *VaultUpdate {
	if v != nil {
		_u.SetRootNoteID(*v)
	}
	return _u
}

// ClearRootNoteID clears the value of the "root_note_id" field.
func (_u *VaultUpdate) ClearRootNoteID() *VaultUpdate {
	_u.mutation.ClearRootNoteID()
	return _u
}

// SetLogoObjectKey sets the "logo_object_key" field.
func (_u *VaultUpdate) SetLogoObjectKey(v string) *VaultUpdate {
	_u.mutation.SetLogoObjectKey(v)
	return _u
}

// SetNillableLogoObjectKey sets the "logo_object_key" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableLogoObjectKey(v *string) *VaultUpdate {
	if v != nil {
		_u.SetLogoObjectKey(*v)
	}
	return _u
}

// ClearLogoObjectKey clears the value of the "logo_object_key" field.
func (_u *VaultUpdate) ClearLogoObjectKey() *VaultUpdate {
	_u.mutation.ClearLogoObjectKey()
	return _u
}

// SetCustomHeadHTML sets the "custom_head_html" field.
func (_u *VaultUpdate) SetCustomHeadHTML(v string) *VaultUpdate {
	_u.mutation.SetCustomHeadHTML(v)
	return _u
}

// SetNillableCustomHeadHTML sets the "custom_head_html" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableCustomHeadHTML(v *string) *VaultUpdate {
	if v != nil {
		_u.SetCustomHeadHTML(*v)
	}
	return _u
}

// ClearCustomHeadHTML clears the value of the "custom_head_html" field.
func (_u *VaultUpdate) ClearCustomHeadHTML() *VaultUpdate {
	_u.mutation.ClearCustomHeadHTML()
	return _u
}

// SetLastPublishAt sets the "last_publish_at" field.
func (_u *VaultUpdate) SetLastPublishAt(v time.Time) *VaultUpdate {
	_u.mutation.SetLastPublishAt(v)
	return _u
}

// SetNillableLastPublishAt sets the "last_publish_at" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableLastPublishAt(v *time.Time) *VaultUpdate {
	if v != nil {
		_u.SetLastPublishAt(*v)
	}
	return _u
}

// ClearLastPublishAt clears the value of the "last_publish_at" field.
func (_u *VaultUpdate) ClearLastPublishAt() *VaultUpdate {
	_u.mutation.ClearLastPublishAt()
	return _u
}

// SetLastPublishStatus sets the "last_publish_status" field.
func (_u *VaultUpdate) SetLastPublishStatus(v string) *VaultUpdate {
	_u.mutation.SetLastPublishStatus(v)
	return _u
}

// SetNillableLastPublishStatus sets the "last_publish_status" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableLastPublishStatus(v *string) *VaultUpdate {
	if v != nil {
		_u.SetLastPublishStatus(*v)
	}
	return _u
}

// SetLastPublishErrorCode sets the "last_publish_error_code" field.
func (_u *VaultUpdate) SetLastPublishErrorCode(v string) *VaultUpdate {
	_u.mutation.SetLastPublishErrorCode(v)
	return _u
}

// SetNillableLastPublishErrorCode sets the "last_publish_error_code" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableLastPublishErrorCode(v *string) *VaultUpdate {
	if v != nil {
		_u.SetLastPublishErrorCode(*v)
	}
	return _u
}

// ClearLastPublishErrorCode clears the value of the "last_publish_error_code" field.
func (_u *VaultUpdate) ClearLastPublishErrorCode() *VaultUpdate {
	_u.mutation.ClearLastPublishErrorCode()
	return _u
}

// SetLastPublishErrorMessage sets the "last_publish_error_message" field.
func (_u *VaultUpdate) SetLastPublishErrorMessage(v string) *VaultUpdate {
	_u.mutation.SetLastPublishErrorMessage(v)
	return _u
}

// SetNillableLastPublishErrorMessage sets the "last_publish_error_message" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableLastPublishErrorMessage(v *string) *VaultUpdate {
	if v != nil {
		_u.SetLastPublishErrorMessage(*v)
	}
	return _u
}

// ClearLastPublishErrorMessage clears the value of the "last_publish_error_message" field.
func (_u *VaultUpdate) ClearLastPublishErrorMessage() *VaultUpdate {
	_u.mutation.ClearLastPublishErrorMessage()
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *VaultUpdate) SetTenant(v *Tenant) *VaultUpdate {
	return _u.SetTenantID(v.ID)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (_u *VaultUpdate) AddNoteIDs(ids ...string) *VaultUpdate {
	_u.mutation.AddNoteIDs(ids...)
	return _u
}

// AddNotes adds the "notes" edges to the Note entity.
func (_u *VaultUpdate) AddNotes(v ...*Note) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNoteIDs(ids...)
}

// AddAssetIDs adds the "assets" edge to the Asset entity by IDs.
func (_u *VaultUpdate) AddAssetIDs(ids ...string) *VaultUpdate {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAssets adds the "assets" edges to the Asset entity.
func (_u *VaultUpdate) AddAssets(v ...*Asset) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// AddNoteLinkIDs adds the "note_links" edge to the NoteLink entity by IDs.
func (_u *VaultUpdate) AddNoteLinkIDs(ids ...string) *VaultUpdate {
	_u.mutation.AddNoteLinkIDs(ids...)
	return _u
}

// AddNoteLinks adds the "note_links" edges to the NoteLink entity.
func (_u *VaultUpdate) AddNoteLinks(v ...*NoteLink) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNoteLinkIDs(ids...)
}

// AddNoteAssetRefIDs adds the "note_asset_refs" edge to the NoteAssetRef entity by IDs.
func (_u *VaultUpdate) AddNoteAssetRefIDs(ids ...string) *VaultUpdate {
	_u.mutation.AddNoteAssetRefIDs(ids...)
	return _u
}

// AddNoteAssetRefs adds the "note_asset_refs" edges to the NoteAssetRef entity.
func (_u *VaultUpdate) AddNoteAssetRefs(v ...*NoteAssetRef) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNoteAssetRefIDs(ids...)
}

// Mutation returns the VaultMutation object of the builder.
func (_u *VaultUpdate) Mutation() *VaultMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *VaultUpdate) ClearTenant() *VaultUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearNotes clears all "notes" edges to the Note entity.
func (_u *VaultUpdate) ClearNotes() *VaultUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// RemoveNoteIDs removes the "notes" edge to Note entities by IDs.
func (_u *VaultUpdate) RemoveNoteIDs(ids ...string) *VaultUpdate {
	_u.mutation.RemoveNoteIDs(ids...)
	return _u
}

// RemoveNotes removes "notes" edges to Note entities.
func (_u *VaultUpdate) RemoveNotes(v ...*Note) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNoteIDs(ids...)
}

// ClearAssets clears all "assets" edges to the Asset entity.
func (_u *VaultUpdate) ClearAssets() *VaultUpdate {
	_u.mutation.ClearAssets()
	return _u
}

// RemoveAssetIDs removes the "assets" edge to Asset entities by IDs.
func (_u *VaultUpdate) RemoveAssetIDs(ids ...string) *VaultUpdate {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAssets removes "assets" edges to Asset entities.
func (_u *VaultUpdate) RemoveAssets(v ...*Asset) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// ClearNoteLinks clears all "note_links" edges to the NoteLink entity.
func (_u *VaultUpdate) ClearNoteLinks() *VaultUpdate {
	_u.mutation.ClearNoteLinks()
	return _u
}

// RemoveNoteLinkIDs removes the "note_links" edge to NoteLink entities by IDs.
func (_u *VaultUpdate) RemoveNoteLinkIDs(ids ...string) *VaultUpdate {
	_u.mutation.RemoveNoteLinkIDs(ids...)
	return _u
}

// RemoveNoteLinks removes "note_links" edges to NoteLink entities.
func (_u *VaultUpdate) RemoveNoteLinks(v ...*NoteLink) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNoteLinkIDs(ids...)
}

// ClearNoteAssetRefs clears all "note_asset_refs" edges to the NoteAssetRef entity.
func (_u *VaultUpdate) ClearNoteAssetRefs() *VaultUpdate {
	_u.mutation.ClearNoteAssetRefs()
	return _u
}

// RemoveNoteAssetRefIDs removes the "note_asset_refs" edge to NoteAssetRef entities by IDs.
func (_u *VaultUpdate) RemoveNoteAssetRefIDs(ids ...string) *VaultUpdate {
	_u.mutation.RemoveNoteAssetRefIDs(ids...)
	return _u
}

// RemoveNoteAssetRefs removes "note_asset_refs" edges to NoteAssetRef entities.
func (_u *VaultUpdate) RemoveNoteAssetRefs(v ...*NoteAssetRef) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNoteAssetRefIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VaultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VaultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VaultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VaultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VaultUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := vault.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Vault.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := vault.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Vault.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncKey(); ok {
		if err := vault.SyncKeyValidator(v); err != nil {
			return &ValidationError{Name: "sync_key", err: fmt.Errorf(`ent: validator failed for field "Vault.sync_key": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vault.tenant"`)
	}
	return nil
}

func (_u *VaultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vault.Table, vault.Columns, sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(vault.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(vault.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(vault.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.SyncKey(); ok {
		_spec.SetField(vault.FieldSyncKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(vault.FieldClientType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootNoteID(); ok {
		_spec.SetField(vault.FieldRootNoteID, field.TypeString, value)
	}
	if _u.mutation.RootNoteIDCleared() {
		_spec.ClearField(vault.FieldRootNoteID, field.TypeString)
	}
	if value, ok := _u.mutation.LogoObjectKey(); ok {
		_spec.SetField(vault.FieldLogoObjectKey, field.TypeString, value)
	}
	if _u.mutation.LogoObjectKeyCleared() {
		_spec.ClearField(vault.FieldLogoObjectKey, field.TypeString)
	}
	if value, ok := _u.mutation.CustomHeadHTML(); ok {
		_spec.SetField(vault.FieldCustomHeadHTML, field.TypeString, value)
	}
	if _u.mutation.CustomHeadHTMLCleared() {
		_spec.ClearField(vault.FieldCustomHeadHTML, field.TypeString)
	}
	if value, ok := _u.mutation.LastPublishAt(); ok {
		_spec.SetField(vault.FieldLastPublishAt, field.TypeTime, value)
	}
	if _u.mutation.LastPublishAtCleared() {
		_spec.ClearField(vault.FieldLastPublishAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPublishStatus(); ok {
		_spec.SetField(vault.FieldLastPublishStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastPublishErrorCode(); ok {
		_spec.SetField(vault.FieldLastPublishErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastPublishErrorCodeCleared() {
		_spec.ClearField(vault.FieldLastPublishErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastPublishErrorMessage(); ok {
		_spec.SetField(vault.FieldLastPublishErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastPublishErrorMessageCleared() {
		_spec.ClearField(vault.FieldLastPublishErrorMessage, field.TypeString)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vault.TenantTable,
			Columns: []string{vault.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vault.TenantTable,
			Columns: []string{vault.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NotesTable,
			Columns: []string{vault.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotesIDs(); len(nodes) > 0 && !_u.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NotesTable,
			Columns: []string{vault.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NotesTable,
			Columns: []string{vault.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.AssetsTable,
			Columns: []string{vault.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetsIDs(); len(nodes) > 0 && !_u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.AssetsTable,
			Columns: []string{vault.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.AssetsTable,
			Columns: []string{vault.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NoteLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteLinksTable,
			Columns: []string{vault.NoteLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNoteLinksIDs(); len(nodes) > 0 && !_u.mutation.NoteLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteLinksTable,
			Columns: []string{vault.NoteLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NoteLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteLinksTable,
			Columns: []string{vault.NoteLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NoteAssetRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteAssetRefsTable,
			Columns: []string{vault.NoteAssetRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNoteAssetRefsIDs(); len(nodes) > 0 && !_u.mutation.NoteAssetRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteAssetRefsTable,
			Columns: []string{vault.NoteAssetRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NoteAssetRefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteAssetRefsTable,
			Columns: []string{vault.NoteAssetRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vault.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VaultUpdateOne is the builder for updating a single Vault entity.
type VaultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VaultMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *VaultUpdateOne) SetTenantID(v string) *VaultUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableTenantID(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *VaultUpdateOne) SetName(v string) *VaultUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableName(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *VaultUpdateOne) SetDomain(v string) *VaultUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableDomain(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *VaultUpdateOne) ClearDomain() *VaultUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetSyncKey sets the "sync_key" field.
func (_u *VaultUpdateOne) SetSyncKey(v string) *VaultUpdateOne {
	_u.mutation.SetSyncKey(v)
	return _u
}

// SetNillableSyncKey sets the "sync_key" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableSyncKey(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetSyncKey(*v)
	}
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *VaultUpdateOne) SetClientType(v string) *VaultUpdateOne {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableClientType(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetRootNoteID sets the "root_note_id" field.
func (_u *VaultUpdateOne) SetRootNoteID(v string) *VaultUpdateOne {
	_u.mutation.SetRootNoteID(v)
	return _u
}

// SetNillableRootNoteID sets the "root_note_id" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableRootNoteID(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetRootNoteID(*v)
	}
	return _u
}

// ClearRootNoteID clears the value of the "root_note_id" field.
func (_u *VaultUpdateOne) ClearRootNoteID() *VaultUpdateOne {
	_u.mutation.ClearRootNoteID()
	return _u
}

// SetLogoObjectKey sets the "logo_object_key" field.
func (_u *VaultUpdateOne) SetLogoObjectKey(v string) *VaultUpdateOne {
	_u.mutation.SetLogoObjectKey(v)
	return _u
}

// SetNillableLogoObjectKey sets the "logo_object_key" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableLogoObjectKey(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetLogoObjectKey(*v)
	}
	return _u
}

// ClearLogoObjectKey clears the value of the "logo_object_key" field.
func (_u *VaultUpdateOne) ClearLogoObjectKey() *VaultUpdateOne {
	_u.mutation.ClearLogoObjectKey()
	return _u
}

// SetCustomHeadHTML sets the "custom_head_html" field.
func (_u *VaultUpdateOne) SetCustomHeadHTML(v string) *VaultUpdateOne {
	_u.mutation.SetCustomHeadHTML(v)
	return _u
}

// SetNillableCustomHeadHTML sets the "custom_head_html" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableCustomHeadHTML(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetCustomHeadHTML(*v)
	}
	return _u
}

// ClearCustomHeadHTML clears the value of the "custom_head_html" field.
func (_u *VaultUpdateOne) ClearCustomHeadHTML() *VaultUpdateOne {
	_u.mutation.ClearCustomHeadHTML()
	return _u
}

// SetLastPublishAt sets the "last_publish_at" field.
func (_u *VaultUpdateOne) SetLastPublishAt(v time.Time) *VaultUpdateOne {
	_u.mutation.SetLastPublishAt(v)
	return _u
}

// SetNillableLastPublishAt sets the "last_publish_at" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableLastPublishAt(v *time.Time) *VaultUpdateOne {
	if v != nil {
		_u.SetLastPublishAt(*v)
	}
	return _u
}

// ClearLastPublishAt clears the value of the "last_publish_at" field.
func (_u *VaultUpdateOne) ClearLastPublishAt() *VaultUpdateOne {
	_u.mutation.ClearLastPublishAt()
	return _u
}

// SetLastPublishStatus sets the "last_publish_status" field.
func (_u *VaultUpdateOne) SetLastPublishStatus(v string) *VaultUpdateOne {
	_u.mutation.SetLastPublishStatus(v)
	return _u
}

// SetNillableLastPublishStatus sets the "last_publish_status" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableLastPublishStatus(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetLastPublishStatus(*v)
	}
	return _u
}

// SetLastPublishErrorCode sets the "last_publish_error_code" field.
func (_u *VaultUpdateOne) SetLastPublishErrorCode(v string) *VaultUpdateOne {
	_u.mutation.SetLastPublishErrorCode(v)
	return _u
}

// SetNillableLastPublishErrorCode sets the "last_publish_error_code" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableLastPublishErrorCode(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetLastPublishErrorCode(*v)
	}
	return _u
}

// ClearLastPublishErrorCode clears the value of the "last_publish_error_code" field.
func (_u *VaultUpdateOne) ClearLastPublishErrorCode() *VaultUpdateOne {
	_u.mutation.ClearLastPublishErrorCode()
	return _u
}

// SetLastPublishErrorMessage sets the "last_publish_error_message" field.
func (_u *VaultUpdateOne) SetLastPublishErrorMessage(v string) *VaultUpdateOne {
	_u.mutation.SetLastPublishErrorMessage(v)
	return _u
}

// SetNillableLastPublishErrorMessage sets the "last_publish_error_message" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableLastPublishErrorMessage(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetLastPublishErrorMessage(*v)
	}
	return _u
}

// ClearLastPublishErrorMessage clears the value of the "last_publish_error_message" field.
func (_u *VaultUpdateOne) ClearLastPublishErrorMessage() *VaultUpdateOne {
	_u.mutation.ClearLastPublishErrorMessage()
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *VaultUpdateOne) SetTenant(v *Tenant) *VaultUpdateOne {
	return _u.SetTenantID(v.ID)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (_u *VaultUpdateOne) AddNoteIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.AddNoteIDs(ids...)
	return _u
}

// AddNotes adds the "notes" edges to the Note entity.
func (_u *VaultUpdateOne) AddNotes(v ...*Note) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNoteIDs(ids...)
}

// AddAssetIDs adds the "assets" edge to the Asset entity by IDs.
func (_u *VaultUpdateOne) AddAssetIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAssets adds the "assets" edges to the Asset entity.
func (_u *VaultUpdateOne) AddAssets(v ...*Asset) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// AddNoteLinkIDs adds the "note_links" edge to the NoteLink entity by IDs.
func (_u *VaultUpdateOne) AddNoteLinkIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.AddNoteLinkIDs(ids...)
	return _u
}

// AddNoteLinks adds the "note_links" edges to the NoteLink entity.
func (_u *VaultUpdateOne) AddNoteLinks(v ...*NoteLink) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNoteLinkIDs(ids...)
}

// AddNoteAssetRefIDs adds the "note_asset_refs" edge to the NoteAssetRef entity by IDs.
func (_u *VaultUpdateOne) AddNoteAssetRefIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.AddNoteAssetRefIDs(ids...)
	return _u
}

// AddNoteAssetRefs adds the "note_asset_refs" edges to the NoteAssetRef entity.
func (_u *VaultUpdateOne) AddNoteAssetRefs(v ...*NoteAssetRef) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNoteAssetRefIDs(ids...)
}

// Mutation returns the VaultMutation object of the builder.
func (_u *VaultUpdateOne) Mutation() *VaultMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *VaultUpdateOne) ClearTenant() *VaultUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearNotes clears all "notes" edges to the Note entity.
func (_u *VaultUpdateOne) ClearNotes() *VaultUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// RemoveNoteIDs removes the "notes" edge to Note entities by IDs.
func (_u *VaultUpdateOne) RemoveNoteIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.RemoveNoteIDs(ids...)
	return _u
}

// RemoveNotes removes "notes" edges to Note entities.
func (_u *VaultUpdateOne) RemoveNotes(v ...*Note) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNoteIDs(ids...)
}

// ClearAssets clears all "assets" edges to the Asset entity.
func (_u *VaultUpdateOne) ClearAssets() *VaultUpdateOne {
	_u.mutation.ClearAssets()
	return _u
}

// RemoveAssetIDs removes the "assets" edge to Asset entities by IDs.
func (_u *VaultUpdateOne) RemoveAssetIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAssets removes "assets" edges to Asset entities.
func (_u *VaultUpdateOne) RemoveAssets(v ...*Asset) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// ClearNoteLinks clears all "note_links" edges to the NoteLink entity.
func (_u *VaultUpdateOne) ClearNoteLinks() *VaultUpdateOne {
	_u.mutation.ClearNoteLinks()
	return _u
}

// RemoveNoteLinkIDs removes the "note_links" edge to NoteLink entities by IDs.
func (_u *VaultUpdateOne) RemoveNoteLinkIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.RemoveNoteLinkIDs(ids...)
	return _u
}

// RemoveNoteLinks removes "note_links" edges to NoteLink entities.
func (_u *VaultUpdateOne) RemoveNoteLinks(v ...*NoteLink) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNoteLinkIDs(ids...)
}

// ClearNoteAssetRefs clears all "note_asset_refs" edges to the NoteAssetRef entity.
func (_u *VaultUpdateOne) ClearNoteAssetRefs() *VaultUpdateOne {
	_u.mutation.ClearNoteAssetRefs()
	return _u
}

// RemoveNoteAssetRefIDs removes the "note_asset_refs" edge to NoteAssetRef entities by IDs.
func (_u *VaultUpdateOne) RemoveNoteAssetRefIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.RemoveNoteAssetRefIDs(ids...)
	return _u
}

// RemoveNoteAssetRefs removes "note_asset_refs" edges to NoteAssetRef entities.
func (_u *VaultUpdateOne) RemoveNoteAssetRefs(v ...*NoteAssetRef) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNoteAssetRefIDs(ids...)
}

// Where appends a list predicates to the VaultUpdate builder.
func (_u *VaultUpdateOne) Where(ps ...predicate.Vault) *VaultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VaultUpdateOne) Select(field string, fields ...string) *VaultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Vault entity.
func (_u *VaultUpdateOne) Save(ctx context.Context) (*Vault, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VaultUpdateOne) SaveX(ctx context.Context) *Vault {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VaultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VaultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VaultUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := vault.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Vault.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := vault.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Vault.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncKey(); ok {
		if err := vault.SyncKeyValidator(v); err != nil {
			return &ValidationError{Name: "sync_key", err: fmt.Errorf(`ent: validator failed for field "Vault.sync_key": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vault.tenant"`)
	}
	return nil
}

func (_u *VaultUpdateOne) sqlSave(ctx context.Context) (_node *Vault, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vault.Table, vault.Columns, sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Vault.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vault.FieldID)
		for _, f := range fields {
			if !vault.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vault.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(vault.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(vault.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(vault.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.SyncKey(); ok {
		_spec.SetField(vault.FieldSyncKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(vault.FieldClientType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootNoteID(); ok {
		_spec.SetField(vault.FieldRootNoteID, field.TypeString, value)
	}
	if _u.mutation.RootNoteIDCleared() {
		_spec.ClearField(vault.FieldRootNoteID, field.TypeString)
	}
	if value, ok := _u.mutation.LogoObjectKey(); ok {
		_spec.SetField(vault.FieldLogoObjectKey, field.TypeString, value)
	}
	if _u.mutation.LogoObjectKeyCleared() {
		_spec.ClearField(vault.FieldLogoObjectKey, field.TypeString)
	}
	if value, ok := _u.mutation.CustomHeadHTML(); ok {
		_spec.SetField(vault.FieldCustomHeadHTML, field.TypeString, value)
	}
	if _u.mutation.CustomHeadHTMLCleared() {
		_spec.ClearField(vault.FieldCustomHeadHTML, field.TypeString)
	}
	if value, ok := _u.mutation.LastPublishAt(); ok {
		_spec.SetField(vault.FieldLastPublishAt, field.TypeTime, value)
	}
	if _u.mutation.LastPublishAtCleared() {
		_spec.ClearField(vault.FieldLastPublishAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPublishStatus(); ok {
		_spec.SetField(vault.FieldLastPublishStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastPublishErrorCode(); ok {
		_spec.SetField(vault.FieldLastPublishErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastPublishErrorCodeCleared() {
		_spec.ClearField(vault.FieldLastPublishErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastPublishErrorMessage(); ok {
		_spec.SetField(vault.FieldLastPublishErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastPublishErrorMessageCleared() {
		_spec.ClearField(vault.FieldLastPublishErrorMessage, field.TypeString)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vault.TenantTable,
			Columns: []string{vault.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vault.TenantTable,
			Columns: []string{vault.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NotesTable,
			Columns: []string{vault.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotesIDs(); len(nodes) > 0 && !_u.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NotesTable,
			Columns: []string{vault.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NotesTable,
			Columns: []string{vault.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.AssetsTable,
			Columns: []string{vault.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetsIDs(); len(nodes) > 0 && !_u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.AssetsTable,
			Columns: []string{vault.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.AssetsTable,
			Columns: []string{vault.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NoteLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteLinksTable,
			Columns: []string{vault.NoteLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNoteLinksIDs(); len(nodes) > 0 && !_u.mutation.NoteLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteLinksTable,
			Columns: []string{vault.NoteLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NoteLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteLinksTable,
			Columns: []string{vault.NoteLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NoteAssetRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteAssetRefsTable,
			Columns: []string{vault.NoteAssetRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNoteAssetRefsIDs(); len(nodes) > 0 && !_u.mutation.NoteAssetRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteAssetRefsTable,
			Columns: []string{vault.NoteAssetRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NoteAssetRefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.NoteAssetRefsTable,
			Columns: []string{vault.NoteAssetRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteassetref.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Vault{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vault.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
