// Code generated by ent, DO NOT EDIT.

package vault

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the vault type in the database.
	Label = "vault"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldSyncKey holds the string denoting the sync_key field in the database.
	FieldSyncKey = "sync_key"
	// FieldClientType holds the string denoting the client_type field in the database.
	FieldClientType = "client_type"
	// FieldRootNoteID holds the string denoting the root_note_id field in the database.
	FieldRootNoteID = "root_note_id"
	// FieldLogoObjectKey holds the string denoting the logo_object_key field in the database.
	FieldLogoObjectKey = "logo_object_key"
	// FieldCustomHeadHTML holds the string denoting the custom_head_html field in the database.
	FieldCustomHeadHTML = "custom_head_html"
	// FieldLastPublishAt holds the string denoting the last_publish_at field in the database.
	FieldLastPublishAt = "last_publish_at"
	// FieldLastPublishStatus holds the string denoting the last_publish_status field in the database.
	FieldLastPublishStatus = "last_publish_status"
	// FieldLastPublishErrorCode holds the string denoting the last_publish_error_code field in the database.
	FieldLastPublishErrorCode = "last_publish_error_code"
	// FieldLastPublishErrorMessage holds the string denoting the last_publish_error_message field in the database.
	FieldLastPublishErrorMessage = "last_publish_error_message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeNotes holds the string denoting the notes edge name in mutations.
	EdgeNotes = "notes"
	// EdgeAssets holds the string denoting the assets edge name in mutations.
	EdgeAssets = "assets"
	// EdgeNoteLinks holds the string denoting the note_links edge name in mutations.
	EdgeNoteLinks = "note_links"
	// EdgeNoteAssetRefs holds the string denoting the note_asset_refs edge name in mutations.
	EdgeNoteAssetRefs = "note_asset_refs"
	// Table holds the table name of the vault in the database.
	Table = "vaults"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "vaults"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// NotesTable is the table that holds the notes relation/edge.
	NotesTable = "notes"
	// NotesInverseTable is the table name for the Note entity.
	// It exists in this package in order to avoid circular dependency with the "note" package.
	NotesInverseTable = "notes"
	// NotesColumn is the table column denoting the notes relation/edge.
	NotesColumn = "vault_id"
	// AssetsTable is the table that holds the assets relation/edge.
	AssetsTable = "assets"
	// AssetsInverseTable is the table name for the Asset entity.
	// It exists in this package in order to avoid circular dependency with the "asset" package.
	AssetsInverseTable = "assets"
	// AssetsColumn is the table column denoting the assets relation/edge.
	AssetsColumn = "vault_id"
	// NoteLinksTable is the table that holds the note_links relation/edge.
	NoteLinksTable = "note_links"
	// NoteLinksInverseTable is the table name for the NoteLink entity.
	// It exists in this package in order to avoid circular dependency with the "notelink" package.
	NoteLinksInverseTable = "note_links"
	// NoteLinksColumn is the table column denoting the note_links relation/edge.
	NoteLinksColumn = "vault_id"
	// NoteAssetRefsTable is the table that holds the note_asset_refs relation/edge.
	NoteAssetRefsTable = "note_asset_refs"
	// NoteAssetRefsInverseTable is the table name for the NoteAssetRef entity.
	// It exists in this package in order to avoid circular dependency with the "noteassetref" package.
	NoteAssetRefsInverseTable = "note_asset_refs"
	// NoteAssetRefsColumn is the table column denoting the note_asset_refs relation/edge.
	NoteAssetRefsColumn = "vault_id"
)

// Columns holds all SQL columns for vault fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldName,
	FieldDomain,
	FieldSyncKey,
	FieldClientType,
	FieldRootNoteID,
	FieldLogoObjectKey,
	FieldCustomHeadHTML,
	FieldLastPublishAt,
	FieldLastPublishStatus,
	FieldLastPublishErrorCode,
	FieldLastPublishErrorMessage,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SyncKeyValidator is a validator for the "sync_key" field. It is called by the builders before save.
	SyncKeyValidator func(string) error
	// DefaultClientType holds the default value on creation for the "client_type" field.
	DefaultClientType string
	// DefaultLastPublishStatus holds the default value on creation for the "last_publish_status" field.
	DefaultLastPublishStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Vault queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// BySyncKey orders the results by the sync_key field.
func BySyncKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncKey, opts...).ToFunc()
}

// ByClientType orders the results by the client_type field.
func ByClientType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientType, opts...).ToFunc()
}

// ByRootNoteID orders the results by the root_note_id field.
func ByRootNoteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRootNoteID, opts...).ToFunc()
}

// ByLogoObjectKey orders the results by the logo_object_key field.
func ByLogoObjectKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoObjectKey, opts...).ToFunc()
}

// ByCustomHeadHTML orders the results by the custom_head_html field.
func ByCustomHeadHTML(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomHeadHTML, opts...).ToFunc()
}

// ByLastPublishAt orders the results by the last_publish_at field.
func ByLastPublishAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPublishAt, opts...).ToFunc()
}

// ByLastPublishStatus orders the results by the last_publish_status field.
func ByLastPublishStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPublishStatus, opts...).ToFunc()
}

// ByLastPublishErrorCode orders the results by the last_publish_error_code field.
func ByLastPublishErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPublishErrorCode, opts...).ToFunc()
}

// ByLastPublishErrorMessage orders the results by the last_publish_error_message field.
func ByLastPublishErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPublishErrorMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByNotesCount orders the results by notes count.
func ByNotesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotesStep(), opts...)
	}
}

// ByNotes orders the results by notes terms.
func ByNotes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAssetsCount orders the results by assets count.
func ByAssetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAssetsStep(), opts...)
	}
}

// ByAssets orders the results by assets terms.
func ByAssets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNoteLinksCount orders the results by note_links count.
func ByNoteLinksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNoteLinksStep(), opts...)
	}
}

// ByNoteLinks orders the results by note_links terms.
func ByNoteLinks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNoteLinksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNoteAssetRefsCount orders the results by note_asset_refs count.
func ByNoteAssetRefsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNoteAssetRefsStep(), opts...)
	}
}

// ByNoteAssetRefs orders the results by note_asset_refs terms.
func ByNoteAssetRefs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNoteAssetRefsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newNotesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotesTable, NotesColumn),
	)
}
func newAssetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AssetsTable, AssetsColumn),
	)
}
func newNoteLinksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NoteLinksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NoteLinksTable, NoteLinksColumn),
	)
}
func newNoteAssetRefsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NoteAssetRefsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NoteAssetRefsTable, NoteAssetRefsColumn),
	)
}
