// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AssetsColumns holds the columns for the "assets" table.
	AssetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "object_key", Type: field.TypeString},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "content_type", Type: field.TypeString},
		{Name: "md5", Type: field.TypeString},
		{Name: "deleted_at", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "vault_id", Type: field.TypeString},
	}
	// AssetsTable holds the schema information for the "assets" table.
	AssetsTable = &schema.Table{
		Name:       "assets",
		Columns:    AssetsColumns,
		PrimaryKey: []*schema.Column{AssetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "assets_tenants_assets",
				Columns:    []*schema.Column{AssetsColumns[10]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "assets_vaults_assets",
				Columns:    []*schema.Column{AssetsColumns[11]},
				RefColumns: []*schema.Column{VaultsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "asset_vault_id_client_id",
				Unique:  true,
				Columns: []*schema.Column{AssetsColumns[11], AssetsColumns[1]},
			},
			{
				Name:    "asset_vault_id",
				Unique:  false,
				Columns: []*schema.Column{AssetsColumns[11]},
			},
			{
				Name:    "asset_vault_id_path",
				Unique:  false,
				Columns: []*schema.Column{AssetsColumns[11], AssetsColumns[2]},
			},
			{
				Name:    "asset_vault_id_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{AssetsColumns[11], AssetsColumns[7]},
			},
			{
				Name:    "asset_vault_id_md5",
				Unique:  false,
				Columns: []*schema.Column{AssetsColumns[11], AssetsColumns[6]},
			},
		},
	}
	// NotesColumns holds the columns for the "notes" table.
	NotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeString, Nullable: true},
		{Name: "hash", Type: field.TypeString, Nullable: true},
		{Name: "mtime", Type: field.TypeString, Nullable: true},
		{Name: "deleted_at", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "vault_id", Type: field.TypeString},
	}
	// NotesTable holds the schema information for the "notes" table.
	NotesTable = &schema.Table{
		Name:       "notes",
		Columns:    NotesColumns,
		PrimaryKey: []*schema.Column{NotesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notes_tenants_notes",
				Columns:    []*schema.Column{NotesColumns[10]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "notes_vaults_notes",
				Columns:    []*schema.Column{NotesColumns[11]},
				RefColumns: []*schema.Column{VaultsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "note_vault_id_client_id",
				Unique:  true,
				Columns: []*schema.Column{NotesColumns[11], NotesColumns[2]},
			},
			{
				Name:    "note_vault_id",
				Unique:  false,
				Columns: []*schema.Column{NotesColumns[11]},
			},
			{
				Name:    "note_vault_id_path",
				Unique:  false,
				Columns: []*schema.Column{NotesColumns[11], NotesColumns[1]},
			},
			{
				Name:    "note_mtime",
				Unique:  false,
				Columns: []*schema.Column{NotesColumns[6]},
			},
		},
	}
	// NoteAssetRefsColumns holds the columns for the "note_asset_refs" table.
	NoteAssetRefsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "note_client_id", Type: field.TypeString},
		{Name: "asset_client_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "vault_id", Type: field.TypeString},
	}
	// NoteAssetRefsTable holds the schema information for the "note_asset_refs" table.
	NoteAssetRefsTable = &schema.Table{
		Name:       "note_asset_refs",
		Columns:    NoteAssetRefsColumns,
		PrimaryKey: []*schema.Column{NoteAssetRefsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "note_asset_refs_vaults_note_asset_refs",
				Columns:    []*schema.Column{NoteAssetRefsColumns[4]},
				RefColumns: []*schema.Column{VaultsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "noteassetref_vault_id_note_client_id_asset_client_id",
				Unique:  true,
				Columns: []*schema.Column{NoteAssetRefsColumns[4], NoteAssetRefsColumns[1], NoteAssetRefsColumns[2]},
			},
			{
				Name:    "noteassetref_vault_id_note_client_id",
				Unique:  false,
				Columns: []*schema.Column{NoteAssetRefsColumns[4], NoteAssetRefsColumns[1]},
			},
			{
				Name:    "noteassetref_vault_id_asset_client_id",
				Unique:  false,
				Columns: []*schema.Column{NoteAssetRefsColumns[4], NoteAssetRefsColumns[2]},
			},
		},
	}
	// NoteLinksColumns holds the columns for the "note_links" table.
	NoteLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "source_client_id", Type: field.TypeString},
		{Name: "target_client_id", Type: field.TypeString},
		{Name: "target_path", Type: field.TypeString, Nullable: true},
		{Name: "link_type", Type: field.TypeString},
		{Name: "display_text", Type: field.TypeString, Nullable: true},
		{Name: "original", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "vault_id", Type: field.TypeString},
	}
	// NoteLinksTable holds the schema information for the "note_links" table.
	NoteLinksTable = &schema.Table{
		Name:       "note_links",
		Columns:    NoteLinksColumns,
		PrimaryKey: []*schema.Column{NoteLinksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "note_links_vaults_note_links",
				Columns:    []*schema.Column{NoteLinksColumns[9]},
				RefColumns: []*schema.Column{VaultsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notelink_vault_id_source_client_id",
				Unique:  false,
				Columns: []*schema.Column{NoteLinksColumns[9], NoteLinksColumns[1]},
			},
			{
				Name:    "notelink_vault_id_target_client_id",
				Unique:  false,
				Columns: []*schema.Column{NoteLinksColumns[9], NoteLinksColumns[2]},
			},
			{
				Name:    "notelink_vault_id_source_client_id_target_client_id",
				Unique:  false,
				Columns: []*schema.Column{NoteLinksColumns[9], NoteLinksColumns[1], NoteLinksColumns[2]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "admin"},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "tenant_id", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_tenants_users",
				Columns:    []*schema.Column{UsersColumns[5]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// VaultsColumns holds the columns for the "vaults" table.
	VaultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "domain", Type: field.TypeString, Nullable: true},
		{Name: "sync_key", Type: field.TypeString},
		{Name: "client_type", Type: field.TypeString, Default: "obsidian"},
		{Name: "root_note_id", Type: field.TypeString, Nullable: true},
		{Name: "logo_object_key", Type: field.TypeString, Nullable: true},
		{Name: "custom_head_html", Type: field.TypeString, Nullable: true},
		{Name: "last_publish_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_publish_status", Type: field.TypeString, Default: "never"},
		{Name: "last_publish_error_code", Type: field.TypeString, Nullable: true},
		{Name: "last_publish_error_message", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "tenant_id", Type: field.TypeString},
	}
	// VaultsTable holds the schema information for the "vaults" table.
	VaultsTable = &schema.Table{
		Name:       "vaults",
		Columns:    VaultsColumns,
		PrimaryKey: []*schema.Column{VaultsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "vaults_tenants_vaults",
				Columns:    []*schema.Column{VaultsColumns[13]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "vault_domain",
				Unique:  true,
				Columns: []*schema.Column{VaultsColumns[2]},
			},
			{
				Name:    "vault_sync_key",
				Unique:  true,
				Columns: []*schema.Column{VaultsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AssetsTable,
		NotesTable,
		NoteAssetRefsTable,
		NoteLinksTable,
		TenantsTable,
		UsersTable,
		VaultsTable,
	}
)

func init() {
	AssetsTable.ForeignKeys[0].RefTable = TenantsTable
	AssetsTable.ForeignKeys[1].RefTable = VaultsTable
	AssetsTable.Annotation = &entsql.Annotation{
		Table: "assets",
	}
	NotesTable.ForeignKeys[0].RefTable = TenantsTable
	NotesTable.ForeignKeys[1].RefTable = VaultsTable
	NotesTable.Annotation = &entsql.Annotation{
		Table: "notes",
	}
	NoteAssetRefsTable.ForeignKeys[0].RefTable = VaultsTable
	NoteAssetRefsTable.Annotation = &entsql.Annotation{
		Table: "note_asset_refs",
	}
	NoteLinksTable.ForeignKeys[0].RefTable = VaultsTable
	NoteLinksTable.Annotation = &entsql.Annotation{
		Table: "note_links",
	}
	TenantsTable.Annotation = &entsql.Annotation{
		Table: "tenants",
	}
	UsersTable.ForeignKeys[0].RefTable = TenantsTable
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	VaultsTable.ForeignKeys[0].RefTable = TenantsTable
	VaultsTable.Annotation = &entsql.Annotation{
		Table: "vaults",
	}
}
