// Code generated by ent, DO NOT EDIT.

package notelink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"mdbrain.dev/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContainsFold(FieldID, id))
}

// VaultID applies equality check predicate on the "vault_id" field. It's identical to VaultIDEQ.
func VaultID(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldVaultID, v))
}

// SourceClientID applies equality check predicate on the "source_client_id" field. It's identical to SourceClientIDEQ.
func SourceClientID(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldSourceClientID, v))
}

// TargetClientID applies equality check predicate on the "target_client_id" field. It's identical to TargetClientIDEQ.
func TargetClientID(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldTargetClientID, v))
}

// TargetPath applies equality check predicate on the "target_path" field. It's identical to TargetPathEQ.
func TargetPath(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldTargetPath, v))
}

// LinkType applies equality check predicate on the "link_type" field. It's identical to LinkTypeEQ.
func LinkType(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldLinkType, v))
}

// DisplayText applies equality check predicate on the "display_text" field. It's identical to DisplayTextEQ.
func DisplayText(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldDisplayText, v))
}

// Original applies equality check predicate on the "original" field. It's identical to OriginalEQ.
func Original(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldOriginal, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldUpdatedAt, v))
}

// VaultIDEQ applies the EQ predicate on the "vault_id" field.
func VaultIDEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldVaultID, v))
}

// VaultIDNEQ applies the NEQ predicate on the "vault_id" field.
func VaultIDNEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldVaultID, v))
}

// VaultIDIn applies the In predicate on the "vault_id" field.
func VaultIDIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldVaultID, vs...))
}

// VaultIDNotIn applies the NotIn predicate on the "vault_id" field.
func VaultIDNotIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldVaultID, vs...))
}

// VaultIDGT applies the GT predicate on the "vault_id" field.
func VaultIDGT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldVaultID, v))
}

// VaultIDGTE applies the GTE predicate on the "vault_id" field.
func VaultIDGTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldVaultID, v))
}

// VaultIDLT applies the LT predicate on the "vault_id" field.
func VaultIDLT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldVaultID, v))
}

// VaultIDLTE applies the LTE predicate on the "vault_id" field.
func VaultIDLTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldVaultID, v))
}

// VaultIDContains applies the Contains predicate on the "vault_id" field.
func VaultIDContains(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContains(FieldVaultID, v))
}

// VaultIDHasPrefix applies the HasPrefix predicate on the "vault_id" field.
func VaultIDHasPrefix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasPrefix(FieldVaultID, v))
}

// VaultIDHasSuffix applies the HasSuffix predicate on the "vault_id" field.
func VaultIDHasSuffix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasSuffix(FieldVaultID, v))
}

// VaultIDEqualFold applies the EqualFold predicate on the "vault_id" field.
func VaultIDEqualFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEqualFold(FieldVaultID, v))
}

// VaultIDContainsFold applies the ContainsFold predicate on the "vault_id" field.
func VaultIDContainsFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContainsFold(FieldVaultID, v))
}

// SourceClientIDEQ applies the EQ predicate on the "source_client_id" field.
func SourceClientIDEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldSourceClientID, v))
}

// SourceClientIDNEQ applies the NEQ predicate on the "source_client_id" field.
func SourceClientIDNEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldSourceClientID, v))
}

// SourceClientIDIn applies the In predicate on the "source_client_id" field.
func SourceClientIDIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldSourceClientID, vs...))
}

// SourceClientIDNotIn applies the NotIn predicate on the "source_client_id" field.
func SourceClientIDNotIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldSourceClientID, vs...))
}

// SourceClientIDGT applies the GT predicate on the "source_client_id" field.
func SourceClientIDGT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldSourceClientID, v))
}

// SourceClientIDGTE applies the GTE predicate on the "source_client_id" field.
func SourceClientIDGTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldSourceClientID, v))
}

// SourceClientIDLT applies the LT predicate on the "source_client_id" field.
func SourceClientIDLT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldSourceClientID, v))
}

// SourceClientIDLTE applies the LTE predicate on the "source_client_id" field.
func SourceClientIDLTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldSourceClientID, v))
}

// SourceClientIDContains applies the Contains predicate on the "source_client_id" field.
func SourceClientIDContains(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContains(FieldSourceClientID, v))
}

// SourceClientIDHasPrefix applies the HasPrefix predicate on the "source_client_id" field.
func SourceClientIDHasPrefix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasPrefix(FieldSourceClientID, v))
}

// SourceClientIDHasSuffix applies the HasSuffix predicate on the "source_client_id" field.
func SourceClientIDHasSuffix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasSuffix(FieldSourceClientID, v))
}

// SourceClientIDEqualFold applies the EqualFold predicate on the "source_client_id" field.
func SourceClientIDEqualFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEqualFold(FieldSourceClientID, v))
}

// SourceClientIDContainsFold applies the ContainsFold predicate on the "source_client_id" field.
func SourceClientIDContainsFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContainsFold(FieldSourceClientID, v))
}

// TargetClientIDEQ applies the EQ predicate on the "target_client_id" field.
func TargetClientIDEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldTargetClientID, v))
}

// TargetClientIDNEQ applies the NEQ predicate on the "target_client_id" field.
func TargetClientIDNEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldTargetClientID, v))
}

// TargetClientIDIn applies the In predicate on the "target_client_id" field.
func TargetClientIDIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldTargetClientID, vs...))
}

// TargetClientIDNotIn applies the NotIn predicate on the "target_client_id" field.
func TargetClientIDNotIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldTargetClientID, vs...))
}

// TargetClientIDGT applies the GT predicate on the "target_client_id" field.
func TargetClientIDGT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldTargetClientID, v))
}

// TargetClientIDGTE applies the GTE predicate on the "target_client_id" field.
func TargetClientIDGTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldTargetClientID, v))
}

// TargetClientIDLT applies the LT predicate on the "target_client_id" field.
func TargetClientIDLT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldTargetClientID, v))
}

// TargetClientIDLTE applies the LTE predicate on the "target_client_id" field.
func TargetClientIDLTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldTargetClientID, v))
}

// TargetClientIDContains applies the Contains predicate on the "target_client_id" field.
func TargetClientIDContains(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContains(FieldTargetClientID, v))
}

// TargetClientIDHasPrefix applies the HasPrefix predicate on the "target_client_id" field.
func TargetClientIDHasPrefix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasPrefix(FieldTargetClientID, v))
}

// TargetClientIDHasSuffix applies the HasSuffix predicate on the "target_client_id" field.
func TargetClientIDHasSuffix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasSuffix(FieldTargetClientID, v))
}

// TargetClientIDEqualFold applies the EqualFold predicate on the "target_client_id" field.
func TargetClientIDEqualFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEqualFold(FieldTargetClientID, v))
}

// TargetClientIDContainsFold applies the ContainsFold predicate on the "target_client_id" field.
func TargetClientIDContainsFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContainsFold(FieldTargetClientID, v))
}

// TargetPathEQ applies the EQ predicate on the "target_path" field.
func TargetPathEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldTargetPath, v))
}

// TargetPathNEQ applies the NEQ predicate on the "target_path" field.
func TargetPathNEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldTargetPath, v))
}

// TargetPathIn applies the In predicate on the "target_path" field.
func TargetPathIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldTargetPath, vs...))
}

// TargetPathNotIn applies the NotIn predicate on the "target_path" field.
func TargetPathNotIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldTargetPath, vs...))
}

// TargetPathGT applies the GT predicate on the "target_path" field.
func TargetPathGT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldTargetPath, v))
}

// TargetPathGTE applies the GTE predicate on the "target_path" field.
func TargetPathGTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldTargetPath, v))
}

// TargetPathLT applies the LT predicate on the "target_path" field.
func TargetPathLT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldTargetPath, v))
}

// TargetPathLTE applies the LTE predicate on the "target_path" field.
func TargetPathLTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldTargetPath, v))
}

// TargetPathContains applies the Contains predicate on the "target_path" field.
func TargetPathContains(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContains(FieldTargetPath, v))
}

// TargetPathHasPrefix applies the HasPrefix predicate on the "target_path" field.
func TargetPathHasPrefix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasPrefix(FieldTargetPath, v))
}

// TargetPathHasSuffix applies the HasSuffix predicate on the "target_path" field.
func TargetPathHasSuffix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasSuffix(FieldTargetPath, v))
}

// TargetPathIsNil applies the IsNil predicate on the "target_path" field.
func TargetPathIsNil() predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIsNull(FieldTargetPath))
}

// TargetPathNotNil applies the NotNil predicate on the "target_path" field.
func TargetPathNotNil() predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotNull(FieldTargetPath))
}

// TargetPathEqualFold applies the EqualFold predicate on the "target_path" field.
func TargetPathEqualFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEqualFold(FieldTargetPath, v))
}

// TargetPathContainsFold applies the ContainsFold predicate on the "target_path" field.
func TargetPathContainsFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContainsFold(FieldTargetPath, v))
}

// LinkTypeEQ applies the EQ predicate on the "link_type" field.
func LinkTypeEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldLinkType, v))
}

// LinkTypeNEQ applies the NEQ predicate on the "link_type" field.
func LinkTypeNEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldLinkType, v))
}

// LinkTypeIn applies the In predicate on the "link_type" field.
func LinkTypeIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldLinkType, vs...))
}

// LinkTypeNotIn applies the NotIn predicate on the "link_type" field.
func LinkTypeNotIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldLinkType, vs...))
}

// LinkTypeGT applies the GT predicate on the "link_type" field.
func LinkTypeGT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldLinkType, v))
}

// LinkTypeGTE applies the GTE predicate on the "link_type" field.
func LinkTypeGTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldLinkType, v))
}

// LinkTypeLT applies the LT predicate on the "link_type" field.
func LinkTypeLT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldLinkType, v))
}

// LinkTypeLTE applies the LTE predicate on the "link_type" field.
func LinkTypeLTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldLinkType, v))
}

// LinkTypeContains applies the Contains predicate on the "link_type" field.
func LinkTypeContains(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContains(FieldLinkType, v))
}

// LinkTypeHasPrefix applies the HasPrefix predicate on the "link_type" field.
func LinkTypeHasPrefix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasPrefix(FieldLinkType, v))
}

// LinkTypeHasSuffix applies the HasSuffix predicate on the "link_type" field.
func LinkTypeHasSuffix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasSuffix(FieldLinkType, v))
}

// LinkTypeEqualFold applies the EqualFold predicate on the "link_type" field.
func LinkTypeEqualFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEqualFold(FieldLinkType, v))
}

// LinkTypeContainsFold applies the ContainsFold predicate on the "link_type" field.
func LinkTypeContainsFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContainsFold(FieldLinkType, v))
}

// DisplayTextEQ applies the EQ predicate on the "display_text" field.
func DisplayTextEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldDisplayText, v))
}

// DisplayTextNEQ applies the NEQ predicate on the "display_text" field.
func DisplayTextNEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldDisplayText, v))
}

// DisplayTextIn applies the In predicate on the "display_text" field.
func DisplayTextIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldDisplayText, vs...))
}

// DisplayTextNotIn applies the NotIn predicate on the "display_text" field.
func DisplayTextNotIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldDisplayText, vs...))
}

// DisplayTextGT applies the GT predicate on the "display_text" field.
func DisplayTextGT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldDisplayText, v))
}

// DisplayTextGTE applies the GTE predicate on the "display_text" field.
func DisplayTextGTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldDisplayText, v))
}

// DisplayTextLT applies the LT predicate on the "display_text" field.
func DisplayTextLT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldDisplayText, v))
}

// DisplayTextLTE applies the LTE predicate on the "display_text" field.
func DisplayTextLTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldDisplayText, v))
}

// DisplayTextContains applies the Contains predicate on the "display_text" field.
func DisplayTextContains(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContains(FieldDisplayText, v))
}

// DisplayTextHasPrefix applies the HasPrefix predicate on the "display_text" field.
func DisplayTextHasPrefix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasPrefix(FieldDisplayText, v))
}

// DisplayTextHasSuffix applies the HasSuffix predicate on the "display_text" field.
func DisplayTextHasSuffix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasSuffix(FieldDisplayText, v))
}

// DisplayTextIsNil applies the IsNil predicate on the "display_text" field.
func DisplayTextIsNil() predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIsNull(FieldDisplayText))
}

// DisplayTextNotNil applies the NotNil predicate on the "display_text" field.
func DisplayTextNotNil() predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotNull(FieldDisplayText))
}

// DisplayTextEqualFold applies the EqualFold predicate on the "display_text" field.
func DisplayTextEqualFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEqualFold(FieldDisplayText, v))
}

// DisplayTextContainsFold applies the ContainsFold predicate on the "display_text" field.
func DisplayTextContainsFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContainsFold(FieldDisplayText, v))
}

// OriginalEQ applies the EQ predicate on the "original" field.
func OriginalEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldOriginal, v))
}

// OriginalNEQ applies the NEQ predicate on the "original" field.
func OriginalNEQ(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldOriginal, v))
}

// OriginalIn applies the In predicate on the "original" field.
func OriginalIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldOriginal, vs...))
}

// OriginalNotIn applies the NotIn predicate on the "original" field.
func OriginalNotIn(vs ...string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldOriginal, vs...))
}

// OriginalGT applies the GT predicate on the "original" field.
func OriginalGT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldOriginal, v))
}

// OriginalGTE applies the GTE predicate on the "original" field.
func OriginalGTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldOriginal, v))
}

// OriginalLT applies the LT predicate on the "original" field.
func OriginalLT(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldOriginal, v))
}

// OriginalLTE applies the LTE predicate on the "original" field.
func OriginalLTE(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldOriginal, v))
}

// OriginalContains applies the Contains predicate on the "original" field.
func OriginalContains(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContains(FieldOriginal, v))
}

// OriginalHasPrefix applies the HasPrefix predicate on the "original" field.
func OriginalHasPrefix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasPrefix(FieldOriginal, v))
}

// OriginalHasSuffix applies the HasSuffix predicate on the "original" field.
func OriginalHasSuffix(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldHasSuffix(FieldOriginal, v))
}

// OriginalIsNil applies the IsNil predicate on the "original" field.
func OriginalIsNil() predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIsNull(FieldOriginal))
}

// OriginalNotNil applies the NotNil predicate on the "original" field.
func OriginalNotNil() predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotNull(FieldOriginal))
}

// OriginalEqualFold applies the EqualFold predicate on the "original" field.
func OriginalEqualFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEqualFold(FieldOriginal, v))
}

// OriginalContainsFold applies the ContainsFold predicate on the "original" field.
func OriginalContainsFold(v string) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldContainsFold(FieldOriginal, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NoteLink {
	return predicate.NoteLink(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasVault applies the HasEdge predicate on the "vault" edge.
func HasVault() predicate.NoteLink {
	return predicate.NoteLink(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VaultTable, VaultColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVaultWith applies the HasEdge predicate on the "vault" edge with a given conditions (other predicates).
func HasVaultWith(preds ...predicate.Vault) predicate.NoteLink {
	return predicate.NoteLink(func(s *sql.Selector) {
		step := newVaultStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NoteLink) predicate.NoteLink {
	return predicate.NoteLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NoteLink) predicate.NoteLink {
	return predicate.NoteLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NoteLink) predicate.NoteLink {
	return predicate.NoteLink(sql.NotPredicates(p))
}
