// Code generated by ent, DO NOT EDIT.

package noteassetref

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the noteassetref type in the database.
	Label = "note_asset_ref"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVaultID holds the string denoting the vault_id field in the database.
	FieldVaultID = "vault_id"
	// FieldNoteClientID holds the string denoting the note_client_id field in the database.
	FieldNoteClientID = "note_client_id"
	// FieldAssetClientID holds the string denoting the asset_client_id field in the database.
	FieldAssetClientID = "asset_client_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeVault holds the string denoting the vault edge name in mutations.
	EdgeVault = "vault"
	// Table holds the table name of the noteassetref in the database.
	Table = "note_asset_refs"
	// VaultTable is the table that holds the vault relation/edge.
	VaultTable = "note_asset_refs"
	// VaultInverseTable is the table name for the Vault entity.
	// It exists in this package in order to avoid circular dependency with the "vault" package.
	VaultInverseTable = "vaults"
	// VaultColumn is the table column denoting the vault relation/edge.
	VaultColumn = "vault_id"
)

// Columns holds all SQL columns for noteassetref fields.
var Columns = []string{
	FieldID,
	FieldVaultID,
	FieldNoteClientID,
	FieldAssetClientID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// VaultIDValidator is a validator for the "vault_id" field. It is called by the builders before save.
	VaultIDValidator func(string) error
	// NoteClientIDValidator is a validator for the "note_client_id" field. It is called by the builders before save.
	NoteClientIDValidator func(string) error
	// AssetClientIDValidator is a validator for the "asset_client_id" field. It is called by the builders before save.
	AssetClientIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the NoteAssetRef queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVaultID orders the results by the vault_id field.
func ByVaultID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVaultID, opts...).ToFunc()
}

// ByNoteClientID orders the results by the note_client_id field.
func ByNoteClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoteClientID, opts...).ToFunc()
}

// ByAssetClientID orders the results by the asset_client_id field.
func ByAssetClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssetClientID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByVaultField orders the results by vault field.
func ByVaultField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVaultStep(), sql.OrderByField(field, opts...))
	}
}
func newVaultStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VaultInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, VaultTable, VaultColumn),
	)
}
